import Link from 'next/link';
export default function Method(){return <main className="method-page"><Link href="/">← DexFraggler</Link><h1>How the search works</h1>
 <h2>Ideal targets</h2><p>Each anchor is a mathematical sine, triangle, square or saw wave with unit peak. Between anchors, the column target is the linear blend of those ideal formulas at that position. Outside the anchors, the nearest shape continues. Targets are independent of every patch and measurement.</p>
 <p>The amber curve shows the ideal formula, including discontinuities. Square and saw waves have infinitely many harmonics. To compare them with a sampled engine, DexFraggler uses every harmonic strictly below Nyquist: 218 at A2, 109 at A3 and 54 at A4, at a 48 kHz sample rate. A perfect band-limited match is a match within that bandwidth.</p>
 <h2>A continuous search</h2><p>A DX7 is a network of six phase-modulated oscillators with discrete tuning, levels, routing and delayed feedback. Its forward equation is known, but its inverse is nonlinear and nonunique. DexFraggler combines a smooth proposal model with legal discrete exploration and native engine measurements. It does not certify a globally optimal patch.</p>
 <p>Each algorithm stays in its row. Harmonic-aware initialization uses the actual column formula; analytic derivatives propagate level changes through all six operators and both feedback delays. Damped least squares and carrier fitting suggest quantized settings, while continuing proposals explore tuning, levels, feedback and optional detuning.</p>
 <p>One native capture is compared with all 32 targets in its row. The scorer represents correlation and target energy as exact finite trigonometric polynomials. It fits phase using adaptive interval bounds, then refines the best phase. This removes a sampled target lookup table without shortening the engine capture or dropping audible target harmonics.</p>
 <h2>Reading progress</h2><p><b>Table average:</b> the sum of current native match scores divided by 1,024. Unmeasured cells contribute zero. Anchor averages use all 32 algorithms in that column. Measured coverage counts cells with current measurements. None of these percentages declares a cell finished; every cell remains eligible for refinement.</p>
 <p><b>Rank colors:</b> cells are ordered against the other current cells, and equal scores share a rank. The colors span that relative ordering, even when the absolute scores are very close. Absolute mode uses the match value itself.</p>
 <h2>Reading a cell</h2><p><b>Measured result:</b> the best patch measured through the compiled Dexed Mark I engine. A2, A3 and A4 are held at velocity 100, with 4,096 measured samples per pitch after 150 ms settling. Phase, DC and a positive output gain are fitted per capture. The worst relative squared RMS error across the three pitches determines the result.</p>
 <p>The displayed match is positive waveform correlation. Relative RMS error is √(1 − correlation²). The dotted curve on the details page is the finite projection used for scoring; the solid amber curve is the ideal formula. Listen plays a short cycle preview.</p>
 <p><b>Model candidates:</b> proposals from the smooth 48 kHz model at 187.5 Hz, using all 127 harmonics below Nyquist. Its objective combines 85% relative waveform squared error and 15% normalized spectral magnitude squared error. Native measurements decide the saved measured champion. Results cover these pitches and capture settings; FM1 hardware has not been measured.</p>
 <h2>Saving and background work</h2><p>Anchors and cell results are saved in your private Site. Reopening the app or restarting the computer resumes them, rebuilding optimizer mechanics from the saved patches. Changing an anchor retains useful patches for remeasurement against the new target.</p>
 <p>The Windows tray app keeps searching while this computer is on. Its menu offers pause, resume, processor priority, table download, new scans, switching scans and table import. Each named scan retains its own anchors and results. Imported patches are queued for fresh measurements against the destination anchors; their uploaded scores are never restored. Importing into a new scan uses the uploaded anchors. Closing the browser is safe. The desktop shortcut opens DexFraggler, and the tray starts at Windows sign-in.</p>
 <p>Download the whole table as JSON, a cell as a DX7 patch, or a complete algorithm row or slice column as a 32-voice SysEx bank. JSON contains the formula anchors, derived targets and cell results.</p>
 <h2>Sources</h2><p><a href="https://github.com/asb2m10/dexed/blob/master/Source/EngineMkI.cpp">Dexed Mark I engine</a> · <a href="https://arxiv.org/abs/2208.06169">DDX7: Differentiable FM Synthesis</a></p>
 </main>}
