import Link from 'next/link';
export default function Method(){return <main className="method-page"><Link href="/">← DexFraggler</Link><h1>How the search works</h1>
 <p>The table contains 32 algorithms and 32 waveform slices. Set anchors on any column. Between anchors, DexFraggler blends sine and cosine Fourier coefficients, preserving harmonic phase and normalizing the resulting waveform. Outside the anchors, it holds the nearest target.</p>
 <h2>A constrained inverse problem</h2><p>A DX7 is a network of six phase-modulated oscillators with discrete tuning, levels, routing and feedback. Even a two-operator pair produces an infinite sideband series:</p><code>y(θ) = A sin(cθ + I sin(mθ))<br/>= A Σ Jₙ(I) sin((c + nm)θ)</code>
 <p>The forward equation is known, but its inverse is nonlinear and nonunique. The search combines exact derivatives of a smooth model with legal discrete proposals and independent native measurements. It does not certify a global optimum.</p>
 <h2>More results from each calculation</h2><p>One measured patch is compared with every target in its algorithm row. A result can improve several cells at once. Row batches share native captures, Fourier projections and cached target data. Each cell also gets a fair turn for focused refinement, with anchor columns first.</p>
 <p>The level fitter propagates six analytic derivatives through nested modulation and both delayed feedback samples. It removes fitted DC and gain directions, solves a damped least-squares step, and quantizes the proposal to legal settings. Ordinary mutations continue exploring tuning, feedback and optional detuning.</p>
 <p>For native scoring, Fourier projections bound which phase positions can win. Positions are skipped only when their upper bound cannot beat another position. Every possible winner and all 28 refinement iterations use the full sampled objective. The capture length, pitches, target resolution and score definition stay fixed.</p>
 <h2>Reading a cell</h2><p><b>Measured result:</b> the best patch verified through the compiled Dexed Mark I engine. A2, A3 and A4 are held at velocity 100, sampled at 48 kHz, with 4,096 measured samples per note after 150 ms settling. One time shift and positive output gain are fitted per capture. Ranking uses the worst relative squared RMS error across the three pitches.</p>
 <p><b>Model candidates:</b> proposals from a smooth 48 kHz oscillator model with sample-delayed feedback. Its objective combines 85% relative waveform squared error and 15% normalized spectral magnitude squared error. Native measurements decide the measured result.</p>
 <p>Correlation is waveform similarity. Relative RMS error is √(1 − correlation²). Targets contain 16, 32 or 64 harmonics, capped below Nyquist at each pitch. Imported cycles are also limited to their source Nyquist. Silent target paths are rejected. FM1 hardware has not been measured; these results cover the stated pitches, duration and settings.</p>
 <h2>Saving and continuous work</h2><p>Anchors, targets and cell results are saved in the private Site. Reopening the app or restarting the computer resumes those results. Changing an anchor preserves patches and remeasures only targets that changed.</p>
 <p>The Windows tray app runs the search while this computer is on. Its menu provides pause, resume, processor priority and table download. Closing the browser is safe. The desktop shortcut opens DexFraggler, and the tray starts at Windows sign-in.</p>
 <p>Download the complete table as JSON, an individual patch, or a complete row or column as a 32-voice DX7 SysEx bank. JSON includes anchors, derived targets and cell results. Loaded patches are measured against the current targets. Standard DX7 hardware plays individual patches; the table is a collection for browsing and export.</p>
 <h2>Sources</h2><p><a href="https://github.com/asb2m10/dexed/blob/master/Source/EngineMkI.cpp">Dexed Mark I engine</a> · <a href="https://arxiv.org/abs/2208.06169">DDX7: Differentiable FM Synthesis</a></p>
 </main>}
