'use client';
import {useMemo,useRef,useState} from 'react';
import {Waves,ArrowLeft,ChevronLeft,ChevronRight,Download,Volume2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableCell,TableRow} from '@/components/ui/table';
import {Choice,Scope,Routing} from './plots';
import {useTable,download,pad} from './table-state';
import {display,sysex} from '@/public/core.mjs';
import {cycle,targetKey,labelAt} from '@/public/targets.mjs';
export default function CellDetails(){
 const t=useTable(),[view,setView]=useState('native'),[pitch,setPitch]=useState('57'),[candidate,setCandidate]=useState(0),audio=useRef<AudioContext|null>(null),algorithm=Math.floor(t.selected/32)+1,slot=t.selected%32,target=t.targets[slot],fresh=t.cell?.target_key===targetKey(target),reference=fresh?t.cell?.reference:null,model=t.cell?.state?.elites?.[candidate];
 const patch=view==='native'?(t.cell?.reference?.patch??t.cell?.patch):(model?.patch??t.cell?.patch),preview=useMemo(()=>patch?display(patch,target,127):null,[patch,target]),measurement=view==='native'?reference?.notes?.find(n=>String(n.note)===pitch):null,wave=measurement?.wave??preview?.wave??[],targetPoints=measurement?.target??preview?.target??[...cycle(target),...cycle(target)];
 const audition=async()=>{audio.current??=new AudioContext();const ac=audio.current;await ac.resume();const b=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate),out=b.getChannelData(0),points=wave.length?wave.slice(0,wave.length/2):cycle(target),peak=Math.max(.001,...points.map(Math.abs)),hz=measurement?440*2**((Number(pitch)-69)/12):187.5;for(let i=0;i<out.length;i++){const pos=(i/ac.sampleRate*hz%1)*points.length,j=Math.floor(pos),f=pos-j;out[i]=(points[j]*(1-f)+points[(j+1)%points.length]*f)/peak*.15*Math.min(1,i/(ac.sampleRate*.02),(out.length-i)/(ac.sampleRate*.06))}const source=ac.createBufferSource();source.buffer=b;source.connect(ac.destination);source.start()};
 return <main className="lab deliberate cell-page"><header className="mast"><a href={'/?cell='+t.selected} className="brand"><Waves/><b>DexFraggler</b></a><a href={'/?cell='+t.selected} className="back-link"><ArrowLeft size={15}/> Wavetable</a></header><section className="cell-workspace"><div className="section-head"><div><h1>Cell details</h1><p className="subtle">{labelAt(t.config,slot)} <span>·</span> Ideal waveform target</p></div><div className="cell-navigation"><Choice label="Algorithm" value={String(algorithm)} onChange={v=>{setCandidate(0);t.select((Number(v)-1)*32+slot)}} items={Array.from({length:32},(_,i)=>({value:String(i+1),label:'Algorithm '+pad(i+1)}))}/><button className="quiet icon-button" aria-label="Previous slice" disabled={slot===0} onClick={()=>{setCandidate(0);t.select(t.selected-1)}}><ChevronLeft size={16}/></button><Choice label="Slice" value={String(slot)} onChange={v=>{setCandidate(0);t.select((algorithm-1)*32+Number(v))}} items={Array.from({length:32},(_,i)=>({value:String(i),label:'Slice '+pad(i+1)}))}/><button className="quiet icon-button" aria-label="Next slice" disabled={slot===31} onClick={()=>{setCandidate(0);t.select(t.selected+1)}}><ChevronRight size={16}/></button></div></div>
 {t.error&&<div role="alert" className="message error">{t.error}{t.error.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/cell" target="_top">Sign in</a>}</div>}
 <section className="panel scope detail-scope"><div className="panel-head"><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="native">Measured result</TabsTrigger><TabsTrigger value="model">Model candidates</TabsTrigger></TabsList></Tabs><span className="legend"><i className="candidate-dot"/> Result <i/> Ideal target</span></div><Scope wave={wave} target={targetPoints} ideal={target} phase={measurement?.phase??0}/><div className="scope-footer"><div className="scope-tools">{measurement?<Choice label="Measurement pitch" value={pitch} onChange={setPitch} items={[{value:'45',label:'A2 · 110 Hz'},{value:'57',label:'A3 · 220 Hz'},{value:'69',label:'A4 · 440 Hz'}]}/>:<span>{patch?(view==='model'?'Model preview':'Model preview · native measurement pending'):'Awaiting a cell result'}</span>}</div><button className="text-button" onClick={()=>void audition().catch(e=>t.setError(e.message))}><Volume2 size={16}/> Listen</button></div></section>
 <div className="stat-row"><div><span>{measurement?'Band-limited match':'Model match'}</span><strong>{(measurement?.score??preview?.score)?.toFixed(6)??'—'}</strong></div><div><span>Relative RMS error</span><strong>{measurement||preview?((measurement?.error??preview!.error)*100).toFixed(3)+'%':'—'}</strong></div><div><span>Worst of A2 / A3 / A4</span><strong>{reference?.score.toFixed(6)??'—'}</strong></div><div><span>Feedback</span><strong>{patch?.feedback??'—'}</strong></div></div>
 {patch&&<div className="detail-grid"><section className="panel parameters"><div className="panel-head"><h3>Operators</h3><button className="text-button" onClick={()=>download(sysex(patch,`A${pad(algorithm)} S${pad(slot+1)}`) as BlobPart,`DexFraggler-A${pad(algorithm)}-S${pad(slot+1)}.syx`,'application/octet-stream')}><Download size={15}/> Download patch</button></div><Table><TableHeader><TableRow><TableHead>Operator</TableHead><TableHead>Mode</TableHead><TableHead>Coarse</TableHead><TableHead>Fine</TableHead><TableHead>Detune</TableHead><TableHead>Level</TableHead></TableRow></TableHeader><TableBody>{patch.operators.map(o=><TableRow key={o.op}><TableCell><b className="op-number">{o.op}</b></TableCell><TableCell>{o.mode?'Fixed':'Ratio'}</TableCell><TableCell>{o.coarse===0&&!o.mode?'½':o.coarse}</TableCell><TableCell>{o.fine}</TableCell><TableCell>{o.detune-7}</TableCell><TableCell className="level-cell"><div className="level-bar"><i style={{width:o.level+'%'}}/></div>{o.level}</TableCell></TableRow>)}</TableBody></Table></section><section className="panel routing-panel"><div className="panel-head"><h3>Algorithm {pad(algorithm)}</h3></div><Routing patch={patch}/></section></div>}
 {view==='model'&&t.cell?.state?.elites?.length?<section className="candidate-strip" aria-label="Model candidates">{t.cell.state.elites.slice(0,8).map((e,i)=><button className={i===candidate?'chosen':''} key={i} onClick={()=>setCandidate(i)}><span>Candidate {i+1}</span><b>{e.score.toFixed(6)}</b></button>)}</section>:null}<p className="detail-note">Dexed measurements use 4,096 samples per pitch. The score uses every target harmonic below Nyquist; the amber curve shows the ideal formula. <a href="/method">Measurement details</a></p></section></main>
}
