'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowDownToLine,ArrowUpRight,Check,FlaskConical,Pause,Play,RefreshCw,Upload,Volume2,Waves} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {SHAPES,MODEL,algorithms,blank,display,sysex,fromSysex,interpolate,validatePatch} from '@/public/core.mjs';
import {Choice,Scope,Routing,Patch} from './plots';
type Elite={patch:Patch;score:number;loss:number;error:number;source?:string};
type Measurement={note:number;score:number;error:number;wave:number[];target:number[]};
type Run={shape:string;running:number;revision:number;updated_at:number;state:{harmonics:number;allowDetune:boolean;evaluations:number;method:string;elites:Elite[];history:{at:number;error:number;score:number}[]};reference:{patch:Patch;score:number;loss:number;notes:Measurement[];testedAt:number;engine:string}|null};
type Data={runs:Run[];workers:{id:string;last_seen:number;engine:string}[]};
function download(data:BlobPart,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Lab(){
 const [target,setTarget]=useState('saw'),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('model'),[note,setNote]=useState('57'),[selected,setSelected]=useState(0),[blend,setBlend]=useState(50),[pair,setPair]=useState('1');
 const file=useRef<HTMLInputElement>(null),live=useRef({target,data}),audio=useRef<AudioContext|null>(null);live.current={target,data};
 const load=useCallback(async()=>{const r=await fetch('/api/lab',{cache:'no-store'}),d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error);setData(prev=>prev?{...d,runs:d.runs.map(x=>{const old=prev.runs.find(r=>r.shape===x.shape);return old&&old.revision>x.revision?old:x})}:d);return d},[]);
 useEffect(()=>{let active=true;const poll=()=>load().then(()=>{if(active)setError('')}).catch(e=>{if(active)setError(e.message)});void poll();const t=setInterval(poll,5000);return()=>{active=false;clearInterval(t)}},[load]);
 const action=useCallback(async(body:Record<string,unknown>)=>{const r=await fetch('/api/lab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);return load()},[load]);
 const perform=async(body:Record<string,unknown>,message='Saved')=>{setBusy(true);setError('');try{await action(body);setNotice(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{
  const doc=document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}};
  if(!doc.modelContext?.registerTool)return;const controller=new AbortController();
  const specs=[
   {name:'get_experiment',description:'Read the selected DexFraggler experiment, model champion, native Dexed measurements and worker status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||Object.keys(input as object).length)throw Error('No input properties accepted.');const d=await load(),r=d.runs.find(x=>x.shape===live.current.target);return {target:live.current.target,running:!!r?.running,candidates:r?.state.evaluations,modelBest:r?.state.elites[0],nativeBest:r?.reference?{patch:r.reference.patch,score:r.reference.score,engine:r.reference.engine,testedAt:r.reference.testedAt,notes:r.reference.notes.map(n=>({note:n.note,score:n.score,error:n.error}))}:null,workers:d.workers}}},
   {name:'select_target',description:'Select the visible waveform experiment without starting a search.',inputSchema:{type:'object',properties:{target:{type:'string',enum:SHAPES}},required:['target'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const x=input as {target:string};if(!x||!SHAPES.includes(x.target)||Object.keys(x).length!==1)throw Error('Specify one valid target.');setTarget(x.target);setSelected(0);live.current.target=x.target;return {selected:x.target}}},
   {name:'set_search_running',description:'Start or pause an experiment. The connected background runner performs computation.',inputSchema:{type:'object',properties:{target:{type:'string',enum:SHAPES},running:{type:'boolean'}},required:['target','running'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const x=input as {target:string;running:boolean};if(x?.running)throw Error('Earlier studies are archived. Use the wavetable map to run the table search.');if(!x||!SHAPES.includes(x.target)||typeof x.running!=='boolean'||Object.keys(x).length!==2)throw Error('Specify target and running.');await action({action:'running',shape:x.target,running:x.running});return {target:x.target,running:x.running}}}
  ];
  for(const s of specs)try{Promise.resolve(doc.modelContext.registerTool(s,{signal:controller.signal})).catch(()=>{})}catch{}
  return()=>controller.abort();
 },[load,action]);
 const run=data?.runs.find(r=>r.shape===target);
 const modelPatch=run?.state.elites[Math.min(selected,(run?.state.elites.length??1)-1)]?.patch??blank();
 const patch:Patch=view==='native'&&run?.reference?run.reference.patch:modelPatch;
 const chart=useMemo(()=>display(patch,target,run?.state.harmonics??32),[patch,target,run?.state.harmonics]);
 const measured=run?.reference?.notes.find(x=>String(x.note)===note),native=view==='native'&&!!measured;
 const wave=native?measured!.wave:chart.wave,targetPoints=native?measured!.target:chart.target,score=native?measured!.score:chart.score,rms=native?measured!.error:chart.error;
 const online=data?.workers.some(w=>Date.now()-w.last_seen<60000),status=run?.running?(online?'Searching in background':'Waiting for runner'):'Paused';
 const audition=async()=>{try{audio.current??=new AudioContext();await audio.current.resume();const ac=audio.current,buffer=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate),out=buffer.getChannelData(0),cycle=wave.slice(0,256),peak=Math.max(1e-5,...cycle.map(Math.abs));for(let i=0;i<out.length;i++){const pos=i/ac.sampleRate*187.5*256,j=Math.floor(pos)%256,f=pos%1,env=Math.min(1,i/(ac.sampleRate*.02),(out.length-i)/(ac.sampleRate*.06));out[i]=(cycle[j]*(1-f)+cycle[(j+1)%256]*f)/peak*.16*env}const src=ac.createBufferSource();src.buffer=buffer;src.connect(ac.destination);src.start();setNotice('Auditioning the displayed cycle at 187.5 Hz. Native measurements use A2, A3 and A4.')}catch(e){setError((e as Error).message)}};
 const importFile=async(f:File)=>{try{if(f.size>5000000)throw Error('Choose a file under 5 MB.');let patches:unknown[];if(f.name.toLowerCase().endsWith('.syx'))patches=[fromSysex(new Uint8Array(await f.arrayBuffer()))];else{const d=JSON.parse(await f.text());patches=Array.isArray(d)?d.map((x:{patch?:Patch})=>x.patch??x):d.state?.elites?.map((e:{patch:Patch})=>e.patch)??d.cells?.slice().sort((a:{score:number},b:{score:number})=>b.score-a.score).map((c:{patch:Patch})=>c.patch)??(d.patch?[d.patch]:[d]);if(d.reference?.patch)patches.unshift(d.reference.patch);const unique=new Map(patches.map(p=>[JSON.stringify(p),p]));patches=Array.from(unique.values()).slice(0,64)}patches.forEach(p=>validatePatch(p));await perform({action:'import',shape:target,patches},'Imported up to 64 distinct candidates and re-scored them. Native patches will be remeasured.');setSelected(0)}catch(e){setError((e as Error).message)}finally{if(file.current)file.current.value=''}};
 const compatible=run?.state.elites.map((e,i)=>({e,i})).filter(({e,i})=>i!==selected&&e.patch.algorithm===modelPatch.algorithm&&e.patch.feedback===modelPatch.feedback)??[];
 return <main className="lab">
  <header className="mast"><div className="brand"><Waves/><b>DexFraggler<span>FM SYNTHESIS LAB</span></b></div><div className="header-right"><a href="/" className="text-link">← Wavetable map</a><span className={'status-dot '+(!online?'offline':'')}>{online?'Background runner connected':'Background runner offline'}</span><button className="icon-button" title="Refresh experiments" aria-label="Refresh experiments" onClick={()=>void load().catch(e=>setError(e.message))}><RefreshCw size={17}/></button></div></header>
  <div className="workbench"><aside className="rail"><p className="eyebrow">EXPERIMENTS</p><h2>Find the shape.</h2>
   <Tabs value={target} onValueChange={v=>{setTarget(v);setSelected(0)}} orientation="vertical"><TabsList className="targets">{SHAPES.map((v:string,i:number)=><TabsTrigger value={v} key={v}><span>0{i+1}</span><b>{v[0].toUpperCase()+v.slice(1)}</b><ArrowUpRight size={16}/></TabsTrigger>)}</TabsList></Tabs>
   <div className="search-settings"><label>Target bandwidth<Choice label="Target bandwidth" value={String(run?.state.harmonics??32)} onChange={v=>void perform({action:'configure',shape:target,harmonics:Number(v),allowDetune:run?.state.allowDetune??false},'Target changed; retained patches re-scored.')} items={[16,32,64].map(x=>({value:String(x),label:x+' harmonics'}))}/></label><div className="switch-line"><label htmlFor="detune">Explore detuning</label><Switch id="detune" checked={run?.state.allowDetune??false} disabled={!run||busy} onCheckedChange={v=>void perform({action:'configure',shape:target,harmonics:run?.state.harmonics??32,allowDetune:v},'Search constraints updated.')}/></div><p>All 32 algorithms · feedback 0–7<br/>Ratio mode · coarse 0–31<br/>Fine and output levels 0–99</p></div>
   <div className="rail-note"><Activity size={20}/><p>Core parameters only.</p><small>Steady envelopes. No LFO, velocity scaling, effects or pitch modulation in the objective.</small><a href="/method" className="text-link">Read the math <ArrowUpRight size={14}/></a></div>
  </aside><section className="workspace">
   <div className="section-head"><div><p className="eyebrow">INVERSE SYNTHESIS / {target.toUpperCase()}</p><h1>Waveform workbench</h1></div><div className="run-control"><span className={run?.running?'running':'muted'}>{status}</span><button disabled={busy||!run||!run.running} onClick={()=>void perform({action:'running',shape:target,running:!run?.running},run?.running?'Search paused. Checkpoint retained.':'Search queued for the background runner.')}>{run?.running?<Pause size={16}/>:<Play size={16}/>} {run?.running?'Pause search':'Archived study'}</button></div></div>
   {error&&<div role="alert" className="message error">{error} {error.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>}</div>}
   {notice&&<div role="status" className="message">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}>×</button></div>}
   <section className="panel scope"><div className="panel-head"><div className="scope-tools"><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="model">Mathematical model</TabsTrigger><TabsTrigger value="native" disabled={!run?.reference}>Dexed measurement</TabsTrigger></TabsList></Tabs>{native&&<Choice label="Measurement pitch" value={note} onChange={setNote} items={[{value:'45',label:'A2 · 110 Hz'},{value:'57',label:'A3 · 220 Hz'},{value:'69',label:'A4 · 440 Hz'}]}/>}</div><span className="legend"><i className="candidate-dot"/> Candidate <i/> Target</span></div><Scope wave={wave} target={targetPoints}/><div className="scope-footer"><span>{native?'Native Mark I · 48 kHz · 4,096 measured samples':'Proposal model · 48 kHz · fixed feedback delay'}</span><button className="text-button" onClick={()=>void audition()}><Volume2 size={16}/> Audition cycle</button></div></section>
   <div className="stat-row"><div><span>Waveform correlation</span><strong>{score.toFixed(6)}</strong></div><div><span>Relative RMS error</span><strong>{(rms*100).toFixed(3)}<small>%</small></strong></div><div><span>Topology / feedback</span><strong>{String(patch.algorithm).padStart(2,'0')} <em>/</em> {patch.feedback}</strong></div><div><span>Candidates scored</span><strong>{run?.state.evaluations.toLocaleString()??'—'}</strong></div></div>
   <div className="detail-grid"><section className="panel parameters"><div className="panel-head"><h3>Operator parameters</h3><button className="text-button" disabled={!run} onClick={()=>download(sysex(patch,'DF '+target) as BlobPart,'DexFraggler-'+target+'-A'+patch.algorithm+'.syx','application/octet-stream')}><ArrowDownToLine size={15}/> DX7 patch</button></div>
   <Table><TableHeader><TableRow><TableHead>Op</TableHead><TableHead>Role</TableHead><TableHead>Coarse</TableHead><TableHead>Fine</TableHead><TableHead>Detune</TableHead><TableHead>Level</TableHead></TableRow></TableHeader><TableBody>{patch.operators.map(o=><TableRow key={o.op}><TableCell><b className="op-number">{o.op}</b></TableCell><TableCell className="muted">{algorithms[patch.algorithm-1].carriers.includes(o.op-1)?'Carrier':'Modulator'}</TableCell><TableCell>{o.coarse===0?'0 (½)':o.coarse}</TableCell><TableCell>{o.fine}</TableCell><TableCell>{o.detune-7>0?'+':''}{o.detune-7}</TableCell><TableCell className="level-cell"><div className="level-bar"><i style={{width:o.level+'%'}}/></div>{o.level}</TableCell></TableRow>)}</TableBody></Table>
   <div className="table-note">{native?'Measured patch':'Model candidate'} · {patch.operators.every(o=>!o.mode)?'Ratio oscillators':'Contains fixed oscillators'} · {native?'Measured at three pitches.':'Native validation is separate.'}</div></section>
   <section className="panel routing-panel"><div className="panel-head"><h3>Algorithm {String(patch.algorithm).padStart(2,'0')}</h3><span>6 OPERATORS</span></div><Routing patch={patch}/><div className="routing-caption"><i/> Carrier <span/> Modulator</div></section></div>
   <Tabs className="lower-tabs" defaultValue="archive"><TabsList variant="line"><TabsTrigger value="archive">Search archive</TabsTrigger><TabsTrigger value="interpolation">Interpolator</TabsTrigger><TabsTrigger value="progress">Convergence</TabsTrigger></TabsList>
    <TabsContent value="archive"><div className="archive-head"><p>Inspect a model candidate or import an existing discovery.</p><div className="inline-actions"><input ref={file} type="file" accept=".json,.syx" hidden onChange={e=>e.target.files?.[0]&&void importFile(e.target.files[0])}/><button className="text-button" disabled={!run||busy} onClick={()=>file.current?.click()}><Upload size={15}/> Import</button><button className="text-button" disabled={!run} onClick={()=>download(JSON.stringify({format:'dexfraggler-experiment',version:1,shape:target,model:MODEL,state:run?.state,reference:run?.reference},null,2),'DexFraggler-'+target+'.json')}><ArrowDownToLine size={15}/> Backup</button></div></div>
    <div className="archive-list">{run?.state.elites.slice(0,8).map((e,i)=><button key={i} className={selected===i&&view==='model'?'selected':''} onClick={()=>{setSelected(i);setView('model')}}><span className="rank">{String(i+1).padStart(2,'0')}</span><b>A{String(e.patch.algorithm).padStart(2,'0')} <span>· FB {e.patch.feedback}</span></b><span className="archive-source">{i===0?'Current champion':e.source?.includes('results/')?'From WaveLab':'Retained candidate'}</span><span className="mono">{e.score.toFixed(6)}</span>{selected===i&&view==='model'?<Check size={15}/>:<ArrowUpRight size={15}/>}</button>)}</div></TabsContent>
    <TabsContent value="interpolation"><section className="panel interpolator"><div><h3>Blend compatible patches</h3><p>Blend effective frequency and linear amplitude, then snap to legal controls. Routing and feedback must agree.</p></div>{compatible.length?<><Choice label="Blend partner" value={compatible.some(x=>String(x.i)===pair)?pair:String(compatible[0].i)} onChange={setPair} items={compatible.map(x=>({value:String(x.i),label:'Candidate '+(x.i+1)+' · '+x.e.score.toFixed(6)}))}/><label>Blend: {blend}%<Slider aria-label="Interpolation blend" value={[blend]} onValueChange={v=>setBlend(v[0])} min={0} max={100} step={1}/></label><button className="action" disabled={busy} onClick={()=>{try{const other=compatible.find(x=>String(x.i)===pair)??compatible[0],p=interpolate(modelPatch,other.e.patch,blend/100);void perform({action:'import',shape:target,patches:[p]},'Interpolated patch evaluated; retained if competitive.')}catch(e){setError((e as Error).message)}}}><FlaskConical size={16}/> Evaluate blend</button></>:<p className="empty-note">Search or import another patch with the same algorithm and feedback to create a compatible pair.</p>}</section></TabsContent>
    <TabsContent value="progress"><section className="panel convergence"><div className="panel-head"><h3>Model error over evaluated candidates</h3><span>LOWER IS BETTER</span></div><svg viewBox="0 0 1000 180" aria-label="Model error convergence"><path d="M20 15V160H980" stroke="#4c5a45" fill="none"/>{run&&run.state.history.length>1&&<polyline points={run.state.history.map((v,i,a)=>(20+960*(v.at-a[0].at)/Math.max(1,a.at(-1)!.at-a[0].at))+','+(20+130*v.error/Math.max(...a.map(x=>x.error),.001))).join(' ')} stroke="#bdde9a" fill="none" strokeWidth="2"/>}</svg><p>{run?.state.method??'Awaiting checkpoint'} · retained improvements only. Candidate counts are not exhaustive coverage.</p></section></TabsContent>
   </Tabs>
   <div className="research-note"><FlaskConical size={18}/><p>{run?.reference?<>Best native correlation across A2, A3 and A4: <b>{run.reference.score.toFixed(6)}</b>. FM1 hardware remains unmeasured.</>:<>Native measurements appear when the Windows runner evaluates this experiment. Model scores alone do not verify Dexed or FM1 accuracy.</>} <a href="/method">Model & measurement notes</a></p></div>
  </section></div><footer>DEXFRAGGLER <span>Mathematical fitting · discrete refinement · native validation</span></footer>
 </main>;
}
