import {tableMetrics} from '@/public/table-metrics.mjs';
import {WAVEFORMS,columnTargets,targetKey} from '@/public/targets.mjs';
type Anchor={slot:number;shape:string};
type TableCell={id:number;current?:boolean;native_score:string|null;model_score:string|null};
type TableData={scan:{id:string;name:string};pendingSeeds:number;running:boolean;revision:number;config:{allowDetune:boolean;anchors:Anchor[]};cells:TableCell[];activeId:number|null};
type CellDetails={reference?:{patch:unknown};patch:unknown;target_key:string};
export function registerTableTools(context:{registerTool:(t:unknown,o:unknown)=>unknown},load:()=>Promise<TableData>,action:(x:Record<string,unknown>)=>Promise<unknown>,select:(id:number)=>void,current:()=>number){
 const controller=new AbortController(),coords=(x:Record<string,unknown>)=>{if(!Number.isInteger(x.algorithm)||Number(x.algorithm)<1||Number(x.algorithm)>32||!Number.isInteger(x.slice)||Number(x.slice)<1||Number(x.slice)>32)throw Error('Algorithm and slice must be 1–32.');return (Number(x.algorithm)-1)*32+Number(x.slice)-1};
 const specs=[
 {name:'get_wavetable',description:'Read the 32×32 table, anchors, average table match, measured coverage, active cell and selected patch.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(x:Record<string,unknown>)=>{if(x&&Object.keys(x).length)throw Error('No input properties accepted.');const d=await load(),id=current(),r=await fetch('/api/table?cell='+id),v=await r.json() as {error:string;cell?:CellDetails};if(!r.ok)throw Error(v.error);return {scan:d.scan,pendingSeeds:d.pendingSeeds,running:d.running,anchors:d.config.anchors,progress:tableMetrics(d.cells),measured:d.cells.filter(c=>c.current&&c.native_score!==null).length,total:1024,activeId:d.activeId,selected:{algorithm:Math.floor(id/32)+1,slice:id%32+1,patch:v.cell?.reference?.patch??v.cell?.patch,current:v.cell?.target_key===targetKey(columnTargets(d.config)[id%32])}}}},
 {name:'select_wavetable_cell',description:'Select an algorithm row and slice column in the visible map.',inputSchema:{type:'object',properties:{algorithm:{type:'integer',minimum:1,maximum:32},slice:{type:'integer',minimum:1,maximum:32}},required:['algorithm','slice'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(x:Record<string,unknown>)=>{if(!x||Object.keys(x).length!==2)throw Error('Specify algorithm and slice.');select(coords(x));return {algorithm:x.algorithm,slice:x.slice}}},
 {name:'set_wavetable_anchor',description:'Set a waveform anchor at a slice (1–32), or remove it to interpolate. Retains patches; affected scores will be remeasured.',inputSchema:{type:'object',properties:{slice:{type:'integer',minimum:1,maximum:32},waveform:{type:'string',enum:[...WAVEFORMS,'blend']}},required:['slice','waveform'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(x:Record<string,unknown>)=>{if(!x||Object.keys(x).length!==2||![...WAVEFORMS,'blend'].includes(String(x.waveform)))throw Error('Specify a slice and waveform.');coords({algorithm:1,slice:x.slice});const d=await load(),anchors=d.config.anchors.filter(a=>a.slot!==Number(x.slice)-1);if(x.waveform!=='blend')anchors.push({slot:Number(x.slice)-1,shape:String(x.waveform)});await action({action:'configure',revision:d.revision,config:{...d.config,anchors}});select(Math.floor(current()/32)*32+Number(x.slice)-1);return {slice:x.slice,waveform:x.waveform}}},
 {name:'set_table_running',description:'Start or pause the single background scheduler for the entire table.',inputSchema:{type:'object',properties:{running:{type:'boolean'}},required:['running'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(x:Record<string,unknown>)=>{if(!x||Object.keys(x).length!==1||typeof x.running!=='boolean')throw Error('Specify running as true or false.');await action({action:'running',running:x.running});return {running:x.running}}}
 ];for(const spec of specs)try{Promise.resolve(context.registerTool(spec,{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort();
}
