'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {Waves,Play,Pause,Download,Settings2,ArrowUpRight,ChevronRight} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Switch} from '@/components/ui/switch';
import {Choice,Scope} from './plots';
import {useTable,download,pad,Target,Config,Cell} from './table-state';
import {WAVEFORMS,idealPoints,labelAt,targetKey} from '@/public/targets.mjs';
import {display} from '@/public/core.mjs';
import {tableMetrics,tablePalette} from '@/public/table-metrics.mjs';
import {bankSysex} from '@/public/bank.mjs';
function Mini({target}:{target:Target}){const p=idealPoints(target,64);return <svg viewBox="0 0 64 32" aria-hidden="true"><polyline points={p.map((v:{x:number;y:number})=>`${v.x*64},${(16-v.y*13).toFixed(4)}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.6"/></svg>}
export default function TablePage(){
 const t=useTable(),{data,config,targets,selected,cell,now}=t,[colors,setColors]=useState('ranked'),[metric,setMetric]=useState('native'),slot=selected%32,algorithm=Math.floor(selected/32)+1,anchor=config.anchors.find(a=>a.slot===slot),target=targets[slot];
 const patch=cell?.reference?.patch??cell?.patch,fresh=cell?.target_key===targetKey(target),note=fresh?cell?.reference?.notes?.find(n=>n.note===57):null;
 const preview=useMemo(()=>patch?display(patch,target,127):null,[patch,target]);
 const lookup=useMemo(()=>new Map(data?.cells.map(c=>[c.id,c])??[]),[data]),palette=useMemo(()=>tablePalette(data?.cells??[],metric,colors),[data?.cells,metric,colors]),coverage=data?.cells.filter(c=>c.current&&c.native_score!==null).length??0,worker=data?.workers.find(w=>now>0&&now>=w.last_seen&&now-w.last_seen<60000),active=new Set(data?.activeIds??(data?.activeId!=null?[data.activeId]:[]));
 const configure=async(next:Config)=>{const latest=await t.load();await t.perform({action:'configure',config:next,revision:latest.revision},'Anchors saved.')};
 const setAnchor=async(shape:string)=>{const anchors=config.anchors.filter(a=>a.slot!==slot);if(shape!=='blend')anchors.push({slot,shape});await configure({...config,anchors})};
 const exportFile=async(kind='json')=>{try{const r=await fetch('/api/table?export=1'),d=await r.json() as {cells:Cell[];error:string};if(!r.ok)throw Error(d.error);if(kind==='json'){download(JSON.stringify(d),'DexFraggler-table.json');return}const cells=Array.from({length:32},(_,i)=>d.cells.find(c=>c.id===(kind==='row'?(algorithm-1)*32+i:i*32+slot)));if(cells.some(c=>!c?.patch))throw Error('All 32 cells need a result before exporting this bank.');download(bankSysex(cells.map(c=>c!.reference?.patch??c!.patch),cells.map(c=>`A${pad(Math.floor(c!.id/32)+1)} S${pad(c!.id%32+1)}`)) as BlobPart,`DexFraggler-${kind}-${pad(kind==='row'?algorithm:slot+1)}.syx`,'application/octet-stream')}catch(e){t.setError((e as Error).message)}};
 return <main className="lab deliberate"><header className="mast"><Link href="/" className="brand"><Waves/><b>DexFraggler</b></Link><div className="header-right"><span className={'status-dot '+(!worker?'offline':'')}>{worker?'Local runner connected':'Local · runner offline'}</span><button className="quiet" disabled={!data||t.busy} onClick={()=>void exportFile()}><Download size={16}/> Download table</button><Sheet><SheetTrigger asChild><button className="quiet icon-button" aria-label="Table settings"><Settings2 size={18}/></button></SheetTrigger><SheetContent className="table-sheet"><SheetHeader><SheetTitle>Table settings</SheetTitle><SheetDescription>Search, display and downloads.</SheetDescription></SheetHeader><div className="sheet-fields"><label className="switch-line">Explore detuning<Switch checked={config.allowDetune} onCheckedChange={v=>void configure({...config,allowDetune:v}).catch(()=>{})}/></label><label>Map colors<Choice label="Map colors" value={colors} onChange={setColors} items={[{value:'ranked',label:'Relative rank'},{value:'absolute',label:'Absolute match'}]}/></label><label>Score source<Choice label="Score source" value={metric} onChange={setMetric} items={[{value:'native',label:'Dexed measurements'},{value:'model',label:'Mathematical model'}]}/></label><button className="quiet" onClick={()=>void exportFile('row')}>Download algorithm {pad(algorithm)} bank</button><button className="quiet" onClick={()=>void exportFile('column')}>Download slice {pad(slot+1)} bank</button><Link href="/method" className="text-link">How the search works <ArrowUpRight size={14}/></Link></div></SheetContent></Sheet></div></header>
 <section className="map-workspace"><div className="section-head"><div><h1>{data?.scan?.name??'Wavetable'}</h1><p className="subtle">32 algorithms <span>×</span> 32 slices <span>·</span> {coverage.toLocaleString()} measured{data?.pendingSeeds?<> <span>·</span> {data.pendingSeeds.toLocaleString()} seeds queued</>:null}{worker?.status?.cellsPerMinute?<> <span>·</span> {Math.round(worker.status.cellsPerMinute)} cells/min</>:null}</p></div><div className="run-control"><span className="muted">{worker?.status?.localPaused?'Paused in system tray':data?.running?data.activeId!=null?`Algorithm ${pad(Math.floor(data.activeId/32)+1)}`:'Scanning':'Paused'}</span><button disabled={!data||t.busy||worker?.status?.localPaused} title={worker?.status?.localPaused?'Resume from the DexFraggler system tray menu':undefined} onClick={()=>void t.perform({action:'running',running:!data?.running},data?.running?'Paused.':'Scanning.').catch(()=>{})}>{data?.running?<Pause size={16}/>:<Play size={16}/>} {data?.running?'Pause':'Scan table'}</button></div></div>
 {t.error&&<div role="alert" className="message error">{t.error}<button aria-label="Dismiss error" onClick={()=>t.setError('')}>×</button></div>}{t.notice&&<div role="status" className="message">{t.notice}<button aria-label="Dismiss message" onClick={()=>t.setNotice('')}>×</button></div>}
 <div className="map-layout"><section className="panel map-panel"><div className="panel-head"><div className="anchor-path">{config.anchors.map((a,i)=><span key={a.slot}>{i>0&&<ChevronRight size={12}/>}<button className="text-button" onClick={()=>t.select((algorithm-1)*32+a.slot)}><b>{pad(a.slot+1)}</b> {a.shape}</button></span>)}</div><span>ANCHORS</span></div><div className="map-scroll"><div className="matrix"><span className="axis-label">ALG</span>{targets.map((target,s)=><button className={'column-label '+(config.anchors.some(a=>a.slot===s)?'anchor-column ':'')+(s===slot?'selected-column':'')} key={s} title={`Slice ${s+1}: ${labelAt(config,s)}`} aria-label={`Edit target for slice ${s+1}`} onClick={()=>t.select((algorithm-1)*32+s)}><Mini target={target}/>{pad(s+1)}</button>)}{Array.from({length:32},(_,a)=><div className="matrix-row" key={a}><button className={'row-label '+(algorithm===a+1?'selected-row':'')} aria-label={`Select algorithm ${a+1}`} onClick={()=>t.select(a*32+slot)}>{pad(a+1)}</button>{Array.from({length:32},(_,s)=>{const id=a*32+s,c=lookup.get(id),paint=palette.get(id),q=paint?.score??null;return <button key={s} title={`A${pad(a+1)} · S${pad(s+1)}${q===null?' · Pending':` · ${q.toFixed(6)} · Rank ${paint!.position} of ${paint!.total}`}`} aria-label={`Algorithm ${a+1}, slice ${s+1}, ${q===null?'pending':q.toFixed(6)}`} aria-pressed={selected===id} className={'map-cell '+(selected===id?'selected ':'')+(active.has(id)?'active ':'')+(q===null&&c?'retained':'')} style={{backgroundColor:paint?.color}} data-table-rank={paint?.position} onClick={()=>t.select(id)} onDoubleClick={()=>{location.href='/cell?cell='+id}} onKeyDown={e=>{const steps:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-32,ArrowDown:32};if(e.key in steps){e.preventDefault();const id2=Math.max(0,Math.min(1023,id+steps[e.key]));t.select(id2);(e.currentTarget.closest('.matrix')?.querySelectorAll('.map-cell')[id2] as HTMLElement)?.focus()}}}/>})}</div>)}</div></div><div className="map-legend"><i/><span>Pending</span><span className="legend-spacer"/><span>{colors==='ranked'?'Lowest rank':'Lower match'}</span><div className="quality-gradient"/><span>{colors==='ranked'?'Highest rank':'Higher match'}</span></div></section>
 <aside className="map-sidebar"><section className="panel selection-card"><div className="selection-title"><span>A{pad(algorithm)} / S{pad(slot+1)}</span><a href={'/cell?cell='+selected} aria-label="Open cell details"><ArrowUpRight size={20}/></a></div><section className="scope"><Scope wave={note?.wave??preview?.wave??[]} target={note?.target??preview?.target??[]} ideal={target} phase={note?.phase??0} compact/></section><div className="selection-score"><b>{fresh&&cell?.reference?cell.reference.score.toFixed(6):'Pending'}</b><span>Band-limited match</span></div><a className="detail-link" href={'/cell?cell='+selected}>Cell details <ArrowUpRight size={15}/></a><div className="anchor-editor"><label>Slice {slot+1} target</label><Choice label={`Anchor at slice ${slot+1}`} value={anchor?.shape??'blend'} onChange={v=>void setAnchor(v).catch(()=>{})} items={[{value:'blend',label:'Interpolate'},...WAVEFORMS.map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)}))]}/><p className="target-caption">Ideal formula · {anchor?anchor.shape:labelAt(config,slot)}</p></div></section><TableProgress cells={data?.cells??[]} config={config} loaded={Boolean(data)}/></aside></div></section></main>
}

function TableProgress({cells,config,loaded}:{cells:import('./table-state').Summary[];config:Config;loaded:boolean}){
 const stats=tableMetrics(cells),percent=(value:number)=>(100*value).toFixed(6);
 return <section className="panel table-progress"><div className="panel-head"><h3>Table progress</h3><span>1,024 CELLS</span></div><div className="progress-body"><div className="progress-primary"><strong>{loaded?percent(stats.tableMatch)+'%':'—'}</strong></div><p className="progress-caption">Average match across the whole table.<br/>Unmeasured cells contribute zero.</p><progress aria-label="Average table match" max={1} value={stats.tableMatch}/><div className="progress-counts"><div><b>{stats.measured.toLocaleString()}</b><span>Measured · {(stats.measured/1024*100).toFixed(1)}%</span></div><div><b>{stats.pending.toLocaleString()}</b><span>Pending</span></div></div><div className="progress-line progress-best"><span>Measured average</span><b>{stats.measuredMatch===null?'—':percent(stats.measuredMatch)+'%'}</b></div>{config.anchors.map(a=><div className="progress-line anchor-progress" key={a.slot}><span>S{pad(a.slot+1)} · {a.shape}</span><b>{percent(stats.columns[a.slot])+'%'}</b></div>)}<p className="progress-footnote">Every cell remains in the search. Scores measure the ideal target’s harmonics below Nyquist at A2, A3 and A4.</p></div></section>;
}
