'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Waves,Play,Pause,Download,Upload,Settings2,ArrowUpRight,ChevronRight} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Switch} from '@/components/ui/switch';
import {Choice,Scope,Patch} from './plots';
import {useTable,download,pad,Target,Config,Cell} from './table-state';
import {WAVEFORMS,cycle,fromCycle,labelAt,targetKey,validateConfig,columnTargets} from '@/public/targets.mjs';
import {display,sysex,fromSysex,validatePatch} from '@/public/core.mjs';
import {bankSysex,fromBank} from '@/public/bank.mjs';
function Mini({target}:{target:Target}){const p=cycle(target,64),peak=Math.max(...p.map(Math.abs),.01);return <svg viewBox="0 0 64 32" aria-hidden="true"><polyline points={p.map((v:number,i:number)=>`${i},${(16-v/peak*13).toFixed(4)}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.6"/></svg>}
function color(t:number){const a=t<.5?[214,69,69]:[242,201,76],b=t<.5?[242,201,76]:[31,111,235],f=t<.5?t*2:(t-.5)*2;return `rgb(${a.map((v,i)=>Math.round(v+(b[i]-v)*f)).join(',')})`}
export default function TablePage(){
 const t=useTable(),{data,config,targets,selected,cell}=t,[colors,setColors]=useState('ranked'),[metric,setMetric]=useState('native'),file=useRef<HTMLInputElement>(null),waveFile=useRef<HTMLInputElement>(null),slot=selected%32,algorithm=Math.floor(selected/32)+1,anchor=config.anchors.find(a=>a.slot===slot),target=targets[slot];
 const patch=cell?.reference?.patch??cell?.patch,fresh=cell?.target_key===targetKey(target),note=fresh?cell?.reference?.notes?.find(n=>n.note===57):null;
 const preview=useMemo(()=>patch?display(patch,target,config.harmonics):null,[patch,target,config.harmonics]);
 const lookup=useMemo(()=>new Map(data?.cells.map(c=>[c.id,c])??[]),[data]),scores=(data?.cells??[]).filter(c=>c.current&&c[metric==='native'?'native_score':'model_score']!==null).map(c=>Number(c[metric==='native'?'native_score':'model_score'])).sort((a,b)=>a-b),coverage=data?.cells.filter(c=>c.current&&c.native_score!==null).length??0,worker=data?.workers.find(w=>Date.now()-w.last_seen<60000),active=new Set(data?.activeIds??(data?.activeId!=null?[data.activeId]:[]));
 const configure=async(next:Config)=>{const latest=await t.load();await t.perform({action:'configure',config:next,revision:latest.revision},'Anchors saved.')};
 const setAnchor=async(shape:string)=>{if(shape==='custom')return;const anchors=config.anchors.filter(a=>a.slot!==slot);if(shape!=='blend')anchors.push({slot,shape});await configure({...config,anchors})};
 const exportFile=async(kind='json')=>{try{const r=await fetch('/api/table?export=1'),d=await r.json() as {cells:Cell[];error:string};if(!r.ok)throw Error(d.error);if(kind==='json'){download(JSON.stringify(d),'DexFraggler-table.json');return}const cells=Array.from({length:32},(_,i)=>d.cells.find(c=>c.id===(kind==='row'?(algorithm-1)*32+i:i*32+slot)));if(cells.some(c=>!c?.patch))throw Error('All 32 cells need a result before exporting this bank.');download(bankSysex(cells.map(c=>c!.reference?.patch??c!.patch),cells.map(c=>`A${pad(Math.floor(c!.id/32)+1)} S${pad(c!.id%32+1)}`)) as BlobPart,`DexFraggler-${kind}-${pad(kind==='row'?algorithm:slot+1)}.syx`,'application/octet-stream')}catch(e){t.setError((e as Error).message)}};
 const importFile=async(f:File)=>{t.setBusy(true);try{if(f.size>15000000)throw Error('Choose a file under 15 MB.');let cells:any[],nextConfig:Config|undefined,snapshot:any;if(f.name.toLowerCase().endsWith('.syx')){const b=new Uint8Array(await f.arrayBuffer()),patches=b.length===4104?fromBank(b):[fromSysex(b)],column=new Set(patches.map((p:Patch)=>p.algorithm)).size===32;cells=patches.map((patch:Patch,i:number)=>({algorithm:patch.algorithm,slot:patches.length===1||column?slot:i,patch}))}else{const d=JSON.parse(await f.text());snapshot=d;nextConfig=d.config;const rows=d.cells??(d.algorithms?Object.values(d.algorithms).flat():null);cells=rows?rows.map((c:any)=>({id:c.id,algorithm:c.algorithm??Math.floor(c.id/32)+1,slot:c.slot??c.id%32,patch:c.reference?.patch??c.patch,result:c})): [{algorithm:validatePatch(d.patch??d).algorithm,slot,patch:validatePatch(d.patch??d)}]}
 if(!cells.length||cells.length>1024)throw Error('A table has up to 1,024 cells.');cells.forEach(c=>{if(validatePatch(c.patch).algorithm!==c.algorithm||!Number.isInteger(c.slot)||c.slot<0||c.slot>31)throw Error('Invalid cell coordinates.')});if(nextConfig){nextConfig=validateConfig(nextConfig);columnTargets(nextConfig);await configure(nextConfig)}for(let i=0;i<cells.length;i+=32){await t.action({action:'import',cells:cells.slice(i,i+32),version:snapshot?.version});t.setNotice(`Loading ${Math.min(i+32,cells.length)} / ${cells.length}`)}t.setNotice('Anchors and patches loaded. Imported patches will be measured.')}catch(e){t.setError((e as Error).message)}finally{t.setBusy(false);if(file.current)file.current.value=''}};
 return <main className="lab deliberate"><header className="mast"><a href="/" className="brand"><Waves/><b>DexFraggler</b></a><div className="header-right"><span className={'status-dot '+(!worker?'offline':'')}>{worker?'Connected':'Offline'}</span><button className="quiet" disabled={!data||t.busy} onClick={()=>void exportFile()}><Download size={16}/> Download table</button><Sheet><SheetTrigger asChild><button className="quiet icon-button" aria-label="Table settings"><Settings2 size={18}/></button></SheetTrigger><SheetContent className="table-sheet"><SheetHeader><SheetTitle>Table settings</SheetTitle><SheetDescription>Targets, display and file controls.</SheetDescription></SheetHeader><div className="sheet-fields"><label>Harmonic limit<Choice label="Harmonic limit" value={String(config.harmonics)} onChange={v=>void configure({...config,harmonics:Number(v)}).catch(()=>{})} items={[16,32,64].map(n=>({value:String(n),label:String(n)}))}/></label><label className="switch-line">Explore detuning<Switch checked={config.allowDetune} onCheckedChange={v=>void configure({...config,allowDetune:v}).catch(()=>{})}/></label><label>Map colors<Choice label="Map colors" value={colors} onChange={setColors} items={[{value:'ranked',label:'Relative rank'},{value:'absolute',label:'Absolute correlation'}]}/></label><label>Score source<Choice label="Score source" value={metric} onChange={setMetric} items={[{value:'native',label:'Dexed measurements'},{value:'model',label:'Mathematical model'}]}/></label><button onClick={()=>file.current?.click()} disabled={!data||t.busy}><Upload size={16}/> Load table or patch</button><button className="quiet" onClick={()=>void exportFile('row')}>Download algorithm {pad(algorithm)} bank</button><button className="quiet" onClick={()=>void exportFile('column')}>Download slice {pad(slot+1)} bank</button><a href="/method" className="text-link">How the search works <ArrowUpRight size={14}/></a></div></SheetContent></Sheet></div></header>
 <input ref={file} type="file" hidden accept=".json,.syx" onChange={e=>e.target.files?.[0]&&void importFile(e.target.files[0])}/><section className="map-workspace"><div className="section-head"><div><h1>Wavetable</h1><p className="subtle">32 algorithms <span>×</span> 32 slices <span>·</span> {coverage.toLocaleString()} measured{worker?.status?.cellsPerMinute?<> <span>·</span> {Math.round(worker.status.cellsPerMinute)} cells/min</>:null}</p></div><div className="run-control"><span className="muted">{worker?.status?.localPaused?'Paused in system tray':data?.running?data.activeId!=null?`Algorithm ${pad(Math.floor(data.activeId/32)+1)}`:'Scanning':'Paused'}</span><button disabled={!data||t.busy||worker?.status?.localPaused} title={worker?.status?.localPaused?'Resume from the DexFraggler system tray menu':undefined} onClick={()=>void t.perform({action:'running',running:!data?.running},data?.running?'Paused.':'Scanning.').catch(()=>{})}>{data?.running?<Pause size={16}/>:<Play size={16}/>} {data?.running?'Pause':'Scan table'}</button></div></div>
 {t.error&&<div role="alert" className="message error">{t.error}{t.error.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in</a>}<button aria-label="Dismiss error" onClick={()=>t.setError('')}>×</button></div>}{t.notice&&<div role="status" className="message">{t.notice}<button aria-label="Dismiss message" onClick={()=>t.setNotice('')}>×</button></div>}
 <div className="map-layout"><section className="panel map-panel"><div className="panel-head"><div className="anchor-path">{config.anchors.map((a,i)=><span key={a.slot}>{i>0&&<ChevronRight size={12}/>}<button className="text-button" onClick={()=>t.select((algorithm-1)*32+a.slot)}><b>{pad(a.slot+1)}</b> {a.name??a.shape}</button></span>)}</div><span>ANCHORS</span></div><div className="map-scroll"><div className="matrix"><span className="axis-label">ALG</span>{targets.map((target,s)=><button className={'column-label '+(config.anchors.some(a=>a.slot===s)?'anchor-column ':'')+(s===slot?'selected-column':'')} key={s} title={`Slice ${s+1}: ${labelAt(config,s)}`} aria-label={`Edit target for slice ${s+1}`} onClick={()=>t.select((algorithm-1)*32+s)}><Mini target={target}/>{pad(s+1)}</button>)}{Array.from({length:32},(_,a)=><div className="matrix-row" key={a}><button className={'row-label '+(algorithm===a+1?'selected-row':'')} aria-label={`Select algorithm ${a+1}`} onClick={()=>t.select(a*32+slot)}>{pad(a+1)}</button>{Array.from({length:32},(_,s)=>{const id=a*32+s,c=lookup.get(id),v=c?.current?c[metric==='native'?'native_score':'model_score']:null,q=v==null?null:Number(v),rank=q==null?0:colors==='absolute'?Math.min(1,-Math.log10(Math.max(1e-6,1-q))/6):scores.length<2||scores[0]===scores.at(-1) ? .5 : scores.findIndex(x=>x>=q)/(scores.length-1);return <button key={s} title={`A${pad(a+1)} · S${pad(s+1)}${q===null?' · Pending':` · ${q.toFixed(6)}`}`} aria-label={`Algorithm ${a+1}, slice ${s+1}, ${q===null?'pending':q.toFixed(6)}`} aria-pressed={selected===id} className={'map-cell '+(selected===id?'selected ':'')+(active.has(id)?'active ':'')+(q===null&&c?'retained':'')} style={{'--cell-color':q===null?undefined:color(rank)} as React.CSSProperties} onClick={()=>t.select(id)} onDoubleClick={()=>{location.href='/cell?cell='+id}} onKeyDown={e=>{const steps:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-32,ArrowDown:32};if(e.key in steps){e.preventDefault();const id2=Math.max(0,Math.min(1023,id+steps[e.key]));t.select(id2);(e.currentTarget.closest('.matrix')?.querySelectorAll('.map-cell')[id2] as HTMLElement)?.focus()}}}/>})}</div>)}</div></div><div className="map-legend"><i/><span>Pending</span><span className="legend-spacer"/><span>Lower match</span><div className="quality-gradient"/><span>Higher match</span></div></section>
 <aside className="panel selection-card"><div className="selection-title"><span>A{pad(algorithm)} / S{pad(slot+1)}</span><a href={'/cell?cell='+selected} aria-label="Open cell details"><ArrowUpRight size={20}/></a></div><section className="scope"><Scope wave={note?.wave??preview?.wave??[]} target={note?.target??preview?.target??[...cycle(target),...cycle(target)]}/></section><div className="selection-score"><b>{fresh&&cell?.reference?cell.reference.score.toFixed(6):'Pending'}</b><span>Correlation</span></div><a className="detail-link" href={'/cell?cell='+selected}>Cell details <ArrowUpRight size={15}/></a><div className="anchor-editor"><label>Slice {slot+1} target</label><Choice label={`Anchor at slice ${slot+1}`} value={anchor?.shape??'blend'} onChange={v=>void setAnchor(v).catch(()=>{})} items={[{value:'blend',label:'Interpolate'},...WAVEFORMS.map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)})),...(anchor?.shape==='custom'?[{value:'custom',label:anchor.name??'Custom'}]:[])]}/><div className="anchor-actions"><button className="text-button" onClick={()=>waveFile.current?.click()}>Load cycle</button><button className="text-button" disabled={!patch} onClick={()=>{try{const wave=note?.wave??preview?.wave;if(!wave)return;const target=fromCycle(wave.slice(0,Math.floor(wave.length/2)),config.harmonics);void configure({...config,anchors:[...config.anchors.filter(a=>a.slot!==slot),{slot,shape:'custom',name:`Cell A${pad(algorithm)} S${pad(slot+1)}`,target}]}).catch(()=>{})}catch(e){t.setError((e as Error).message)}}}>Use result</button></div><input ref={waveFile} type="file" hidden accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)void(async()=>{if(f.size>1000000)throw Error('Choose a cycle under 1 MB.');const d=JSON.parse(await f.text()),target=fromCycle(d.samples??d,config.harmonics);await configure({...config,anchors:[...config.anchors.filter(a=>a.slot!==slot),{slot,shape:'custom',name:f.name.replace(/\.json$/i,''),target}]})})().catch(e=>t.setError(e.message));e.target.value=''}}/></div></aside></div></section></main>
}
