'use client';
import {useState,useEffect,useCallback,useMemo,useRef} from 'react';
import {Waves,ArrowUpRight,Play,Pause,Download,Upload,Volume2,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Choice,Scope,Routing,Patch} from './plots';
import {registerTableTools} from './table-tools';
import {DEFAULT_CONFIG,WAVEFORMS,columnTargets,cycle,fromCycle,labelAt,targetKey} from '@/public/targets.mjs';
import {display,render,sysex,fromSysex,validatePatch} from '@/public/core.mjs';
import {bankSysex,fromBank} from '@/public/bank.mjs';
type Target={kind:string;sin:number[];cos:number[]};
type Anchor={slot:number;shape:string;name?:string;target?:Target};
type Config={harmonics:number;allowDetune:boolean;anchors:Anchor[]};
type Summary={id:number;current:boolean;visits:number;evaluations:number;model_score:string|null;native_score:string|null;revision:number;last_error?:string|null;failed_until?:number};
type Measurement={note:number;score:number;error:number;wave:number[];target:number[]};
type Cell={id:number;patch:Patch;target_key:string;state:{elites:{patch:Patch;score:number;loss:number}[];evaluations:number}|null;reference:{patch:Patch;score:number;loss:number;notes:Measurement[]}|null;provenance:{score?:number;source?:string;model?:string}|null;current?:boolean};
type Data={config:Config;revision:number;generation:number;running:boolean;activeId:number|null;cells:Summary[];workers:{last_seen:number}[]};
function download(data:BlobPart,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const pad=(n:number)=>String(n).padStart(2,'0');
function MiniWave({target}:{target:Target}){const points=cycle(target,64),peak=Math.max(...points.map(Math.abs),.01);return <svg viewBox="0 0 64 32" aria-hidden="true"><polyline points={points.map((v:number,i:number)=>`${i},${16-v/peak*13}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.6"/></svg>}
function color(t:number){const a=t<.5?[214,69,69]:[242,201,76],b=t<.5?[242,201,76]:[31,111,235],f=t<.5?t*2:(t-.5)*2;return `rgb(${a.map((v,i)=>Math.round(v+(b[i]-v)*f)).join(',')})`}
export default function Wavetable(){
 const [selected,setSelected]=useState(0),[data,setData]=useState<Data|null>(null),[cell,setCell]=useState<Cell|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[metric,setMetric]=useState('native'),[colors,setColors]=useState('ranked'),[note,setNote]=useState('57');
 const file=useRef<HTMLInputElement>(null),waveFile=useRef<HTMLInputElement>(null),audio=useRef<AudioContext|null>(null),live=useRef({selected,data});live.current={selected,data};
 const config:Config=data?.config??DEFAULT_CONFIG,targets=useMemo(()=>columnTargets(config),[config]),slot=selected%32,algorithm=Math.floor(selected/32)+1,target=targets[slot],anchor=config.anchors.find(a=>a.slot===slot);
 const load=useCallback(async()=>{const r=await fetch('/api/table',{cache:'no-store'}),d=await r.json() as Data&{error:string};if(!r.ok)throw Error(d.error);setData(prev=>prev&&prev.revision>d.revision?prev:d);return d as Data},[]);
 const action=useCallback(async(body:Record<string,unknown>)=>{const r=await fetch('/api/table',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);return load()},[load]);
 const perform=async(body:Record<string,unknown>,message='Saved')=>{setBusy(true);setError('');try{await action(body);setNotice(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{let alive=true;const poll=()=>load().catch(e=>{if(alive)setError(e.message)});void poll();const timer=setInterval(poll,3000);return()=>{alive=false;clearInterval(timer)}},[load]);
 useEffect(()=>{let alive=true;setCell(prev=>prev?.id===selected?prev:null);fetch('/api/table?cell='+selected,{cache:'no-store'}).then(async r=>{const d=await r.json() as {error:string;cell:Cell|null};if(!r.ok)throw Error(d.error);if(alive)setCell(d.cell)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[selected,data?.revision]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(context)return registerTableTools(context,load,action,id=>{setSelected(id);live.current.selected=id},()=>live.current.selected)},[load,action]);
 const configure=(next:Config)=>perform({action:'configure',config:next,revision:data?.revision},'Target path saved. Affected cells retain their patches and will be remeasured.');
 const setAnchor=(shape:string)=>{if(shape==='custom')return;const anchors=config.anchors.filter(a=>a.slot!==slot);if(shape!=='blend')anchors.push({slot,shape});void configure({...config,anchors})};
 const lookup=useMemo(()=>new Map(data?.cells.map(c=>[c.id,c])??[]),[data]),fresh=cell?.target_key===targetKey(target),patch=(metric==='native'?cell?.reference?.patch:null)??cell?.patch;
 const chart=useMemo(()=>patch?display(patch,target,config.harmonics):null,[patch,target,config.harmonics]),measurement=fresh&&metric==='native'?cell?.reference?.notes.find(n=>String(n.note)===note):null;
 const targetWave=measurement?.target??chart?.target??[...cycle(target),...cycle(target)],wave=measurement?.wave??chart?.wave??[],score=measurement?.score??chart?.score,rms=measurement?.error??chart?.error;
 const scores=data?.cells.filter(c=>c.current&&c[metric==='native'?'native_score':'model_score']!==null).map(c=>Number(c[metric==='native'?'native_score':'model_score'])).sort((a,b)=>a-b)??[];
 const coverage=data?.cells.filter(c=>c.current&&c.native_score!==null).length??0,online=data?.workers.some(w=>Date.now()-w.last_seen<60000),active=data?.activeId;
 const exportFile=async(kind:string)=>{try{const r=await fetch('/api/table?export=1'),d=await r.json() as {error:string;cells:Cell[]};if(!r.ok)throw Error(d.error);if(kind==='json'){download(JSON.stringify(d),'DexFraggler-table.json');return}const cells=Array.from({length:32},(_,i)=>(d.cells as Cell[]).find(c=>c.id===(kind==='row'?(algorithm-1)*32+i:i*32+slot)));if(cells.some(c=>!c?.patch))throw Error('This bank has empty cells. Solve or import all 32 before exporting.');const patches=cells.map(c=>metric==='native'&&c!.reference?c!.reference.patch:c!.patch);download(bankSysex(patches,cells.map(c=>`A${pad(Math.floor(c!.id/32)+1)} S${pad(c!.id%32+1)}`)) as BlobPart,`DexFraggler-${kind}-${kind==='row'?pad(algorithm):pad(slot+1)}.syx`,'application/octet-stream');setNotice(cells.some(c=>!c!.current)?'Bank exported with retained patches; some cells await measurement.':'32-voice bank exported.')}catch(e){setError((e as Error).message)}};
 const importFile=async(f:File)=>{setBusy(true);try{if(f.size>15000000)throw Error('Choose a table or patch under 15 MB.');let cells:{algorithm:number;slot:number;patch:Patch;provenance?:unknown}[],nextConfig:Config|undefined;
 if(f.name.toLowerCase().endsWith('.syx')){const b=new Uint8Array(await f.arrayBuffer());if(b.length===4104){const bank=fromBank(b),column=new Set(bank.map((p:Patch)=>p.algorithm)).size===32;cells=bank.map((patch:Patch,i:number)=>({algorithm:patch.algorithm,slot:column?slot:i,patch}))}else {const p=fromSysex(b);cells=[{algorithm:p.algorithm,slot,patch:p}]}}else{const d=JSON.parse(await f.text());nextConfig=d.config;const rows=d.cells??(d.algorithms?Object.values(d.algorithms).flat():null);cells=rows?rows.map((c:Cell&{algorithm?:number;slot?:number})=>({algorithm:c.algorithm??Math.floor(c.id/32)+1,slot:c.slot??c.id%32,patch:c.reference?.patch??c.patch,provenance:c.provenance})): [{algorithm:validatePatch(d.patch??d).algorithm,slot,patch:validatePatch(d.patch??d)}]}
 if(!cells.length||cells.length>1024)throw Error('A table can contain up to 1,024 cells.');cells.forEach(c=>{const p=validatePatch(c.patch);if(p.algorithm!==c.algorithm||!Number.isInteger(c.slot)||c.slot<0||c.slot>31)throw Error('Invalid table coordinates.')});if(nextConfig){const latest=await load();await action({action:'configure',config:nextConfig,revision:latest.revision})}for(let i=0;i<cells.length;i+=64){await action({action:'import',cells:cells.slice(i,i+64)});setNotice(`Imported ${Math.min(i+64,cells.length)} / ${cells.length} cells`)}setNotice('Patches imported as seeds. New scores appear after measurement.')}catch(e){setError((e as Error).message)}finally{setBusy(false);if(file.current)file.current.value=''}};
 const captureTarget=async(samples:number[],name:string)=>{const target=fromCycle(samples,config.harmonics);await configure({...config,anchors:[...config.anchors.filter(a=>a.slot!==slot),{slot,shape:'custom',name,target}]})};
 const audition=async()=>{try{audio.current??=new AudioContext();await audio.current.resume();const ac=audio.current,source=ac.createBufferSource(),b=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate),out=b.getChannelData(0),points=wave.length?wave.slice(0,Math.floor(wave.length/2)):cycle(target),peak=Math.max(.001,...points.map(Math.abs));for(let i=0;i<out.length;i++){const pos=(i/ac.sampleRate*187.5%1)*points.length,j=Math.floor(pos),f=pos-j;out[i]=(points[j]*(1-f)+points[(j+1)%points.length]*f)/peak*.14*Math.min(1,i/(ac.sampleRate*.02),(out.length-i)/(ac.sampleRate*.06))}source.buffer=b;source.connect(ac.destination);source.start()}catch(e){setError((e as Error).message)}};
 return <main className="lab map-lab"><header className="mast"><div className="brand"><Waves/><b>DexFraggler<span>DX7 WAVETABLE LAB</span></b></div><div className="header-right"><span className={'status-dot '+(!online?'offline':'')}>{online?'Background search connected':'Background search offline'}</span><a href="/studies">Earlier studies <ArrowUpRight size={14}/></a></div></header><section className="map-workspace">
 <div className="section-head"><div><p className="eyebrow">32 ALGORITHMS × 32 SLICES</p><h1>The waveform map</h1></div><div className="run-control"><span className="muted">{data?.running?active!=null?`Solving A${pad(Math.floor(active/32)+1)} · S${pad(active%32+1)}`:online?'Choosing next cell':'Waiting for runner':'Table paused'}</span><button disabled={!data||busy} onClick={()=>void perform({action:'running',running:!data?.running},data?.running?'Table paused. All solutions retained.':'The background search is solving the table.')} >{data?.running?<Pause size={16}/>:<Play size={16}/>} {data?.running?'Pause table':'Solve table'}</button></div></div>
 {error&&<div className="message error" role="alert">{error} {error.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}{notice&&<div className="message" role="status">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}>×</button></div>}
 <div className="map-toolbar"><Tabs value={metric} onValueChange={setMetric}><TabsList><TabsTrigger value="native">Dexed measurements</TabsTrigger><TabsTrigger value="model">Model proposals</TabsTrigger></TabsList></Tabs><div className="map-count"><b>{coverage.toLocaleString()}</b> / 1,024 measured <span>·</span> {data?.cells.length??0} patches retained</div><Choice label="Map color scale" value={colors} onChange={setColors} items={[{value:'ranked',label:'Ranked colors'},{value:'absolute',label:'Absolute colors'}]}/></div>
 <div className="map-layout"><section className="panel map-panel"><div className="panel-head"><div className="anchor-path">{config.anchors.map((a,i)=><span key={a.slot}>{i>0&&<ChevronRight size={12}/>}<button className="text-button" onClick={()=>setSelected((algorithm-1)*32+a.slot)}><b>{pad(a.slot+1)}</b> {a.name??a.shape}</button></span>)}</div><span>CLICK A COLUMN TO SET ITS TARGET</span></div>
 <div className="map-scroll"><div className="matrix"><span className="axis-label">ALG</span>{targets.map((t:Target,s:number)=><button title={`Slice ${s+1}: ${labelAt(config,s)}`} aria-label={`Edit target for slice ${s+1}`} className={'column-label '+(config.anchors.some(a=>a.slot===s)?'anchor-column':'')+(s===slot?' selected-column':'')} key={'s'+s} onClick={()=>setSelected((algorithm-1)*32+s)}><MiniWave target={t}/>{pad(s+1)}</button>)}
 {Array.from({length:32},(_,a)=><div className="matrix-row" key={a}><button className={'row-label '+(a+1===algorithm?'selected-row':'')} aria-label={`Select algorithm ${a+1}`} onClick={()=>setSelected(a*32+slot)}>{pad(a+1)}</button>{Array.from({length:32},(_,s)=>{const id=a*32+s,c=lookup.get(id),value=c?.current?c[metric==='native'?'native_score':'model_score']:null,q=value==null?null:Number(value),t=q==null?0:colors==='absolute'?Math.min(1,-Math.log10(Math.max(1e-6,1-q))/6):scores.length<2?.5:scores.findIndex(v=>v>=q)/Math.max(1,scores.length-1);return <button key={s} title={`A${pad(a+1)} · S${pad(s+1)} · ${labelAt(config,s)}\n${q===null?c?'Retained patch · awaiting measurement':'Empty':`${metric==='native'?'Dexed':'Model'} correlation ${q.toFixed(6)}`}`} aria-label={`Algorithm ${a+1}, slice ${s+1}, ${q===null?c?'awaiting measurement':'empty':q.toFixed(6)}`} aria-pressed={selected===id} className={'map-cell '+(selected===id?'selected ':'')+(active===id?'active ':'')+(q===null&&c?'retained':'')} style={{'--cell-color':q===null?undefined:color(t)} as React.CSSProperties} onClick={()=>setSelected(id)} onKeyDown={e=>{const move:{[key:string]:number}={ArrowLeft:-1,ArrowRight:1,ArrowUp:-32,ArrowDown:32};if(e.key in move){e.preventDefault();const next=Math.max(0,Math.min(1023,id+move[e.key]));setSelected(next);(e.currentTarget.closest('.matrix')?.querySelectorAll('.map-cell')[next] as HTMLElement)?.focus()}}}/>})}</div>)}
 </div></div><div className="map-legend"><i/><span>Empty / awaiting measurement</span><span className="legend-spacer"/><span>Lower match</span><div className="quality-gradient"/><span>Higher match</span></div><p className="map-footnote">{colors==='ranked'?'Colors rank measured cells relative to each other.':'Absolute color tracks correlation deficit from 1 to one part per million.'} {metric==='native'?'Scores use the worst of A2, A3 and A4.':'Proposal scores are not native measurements.'}</p></section>
 <aside className="panel cell-inspector"><p className="eyebrow">SELECTED CELL</p><h2>A{pad(algorithm)} <span className="muted">/</span> Slice {pad(slot+1)}</h2><div className="anchor-editor"><label>Target at slice {slot+1}</label><Choice label={`Anchor at slice ${slot+1}`} value={anchor?.shape??'blend'} onChange={setAnchor} items={[{value:'blend',label:'Interpolate between anchors'},...WAVEFORMS.map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)})),...(anchor?.shape==='custom'?[{value:'custom',label:anchor.name??'Custom waveform'}]:[])]}/><p className="muted">{anchor?'Anchor · defines the path for every algorithm.':labelAt(config,slot)+'. Targets blend between the nearest anchors.'}</p><div className="inline-actions"><button className="text-button" disabled={!patch||busy} onClick={()=>{try{if(patch)void captureTarget(wave.length?wave.slice(0,Math.floor(wave.length/2)):Array.from(render(patch,256) as Float64Array),`A${pad(algorithm)} S${pad(slot+1)} cycle`).catch(e=>setError(e.message))}catch(e){setError((e as Error).message)}}}>Use this patch’s cycle</button><input ref={waveFile} type="file" hidden accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>1000000)setError('A single-cycle JSON must be under 1 MB.');else if(f)void f.text().then(t=>{const d=JSON.parse(t);return captureTarget(d.samples??d,f.name.replace(/\.json$/i,''))}).catch(e=>setError(e.message));e.target.value=''}}/><button className="text-button" disabled={busy||!data} onClick={()=>waveFile.current?.click()}>Load cycle</button></div></div>
 <section className="scope cell-scope"><Scope wave={wave} target={targetWave}/><div className="scope-footer"><span>{measurement?'Native capture':patch?'Model preview':'Target waveform'}</span><button className="text-button" aria-label="Audition selected cycle" onClick={()=>void audition()}><Volume2 size={15}/></button></div></section>
 {measurement&&<Choice label="Inspection pitch" value={note} onChange={setNote} items={[{value:'45',label:'A2 · 110 Hz'},{value:'57',label:'A3 · 220 Hz'},{value:'69',label:'A4 · 440 Hz'}]}/>}
 <div className="cell-stats"><div><span>Correlation</span><b>{score?.toFixed(6)??'—'}</b></div><div><span>RMS error</span><b>{rms==null?'—':(rms*100).toFixed(3)+'%'}</b></div></div><p className="cell-measure-note">{!patch?'No patch yet. Solve the table to populate this cell.':!fresh?'Retained patch preview. This cell awaits measurement against the current target.':metric==='native'?'Measured through Dexed Mark I. FM1 hardware remains unmeasured.':'Smooth mathematical proposal. Switch to Dexed measurements for engine validation.'}</p>
 {patch&&<><div className="panel-head patch-head"><h3>Feedback {patch.feedback}</h3><button className="text-button" onClick={()=>download(sysex(patch,`A${pad(algorithm)} S${pad(slot+1)}`) as BlobPart,`DexFraggler-A${pad(algorithm)}-S${pad(slot+1)}.syx`,'application/octet-stream')}><Download size={14}/> Patch</button></div><Table><TableHeader><TableRow><TableHead>Op</TableHead><TableHead>Coarse</TableHead><TableHead>Fine</TableHead><TableHead>Det.</TableHead><TableHead>Level</TableHead></TableRow></TableHeader><TableBody>{patch.operators.map(o=><TableRow key={o.op}><TableCell>{o.op}</TableCell><TableCell>{o.coarse}{o.mode?' F':''}</TableCell><TableCell>{o.fine}</TableCell><TableCell>{o.detune-7}</TableCell><TableCell>{o.level}</TableCell></TableRow>)}</TableBody></Table><div className="map-routing"><Routing patch={patch}/></div></>}
 {cell?.provenance&&<details className="provenance"><summary>Original discovery</summary><p>{cell.provenance.source??'Imported patch'}<br/>Historical score: {cell.provenance.score?.toFixed(6)??'not recorded'}. Historical scores do not color this map.</p></details>}
 </aside></div>
 <section className="map-bottom"><div className="panel map-settings"><h3>Table settings</h3><div className="settings-line"><Choice label="Target harmonics" value={String(config.harmonics)} onChange={v=>void configure({...config,harmonics:Number(v)})} items={[16,32,64].map(n=>({value:String(n),label:n+' harmonics'}))}/><label className="switch-line">Explore detuning <Switch checked={config.allowDetune} disabled={busy||!data} onCheckedChange={allowDetune=>void configure({...config,allowDetune})}/></label></div><p>One search visits every cell, starts with anchors, and reuses neighbors within the same algorithm. Closing this page keeps it running while the connected computer is on. <a href="/method">Math & measurement notes ↗</a></p></div><div className="panel map-exports"><h3>Use the table</h3><div className="inline-actions"><button disabled={!data||busy} onClick={()=>void exportFile('row')}><Download size={15}/> Algorithm {pad(algorithm)} bank</button><button disabled={!data||busy} onClick={()=>void exportFile('column')}><Download size={15}/> Slice {pad(slot+1)} bank</button><button className="text-button" disabled={!data} onClick={()=>void exportFile('json')}>Backup table</button><button className="text-button" disabled={!data||busy} onClick={()=>file.current?.click()}><Upload size={14}/> Import</button><input ref={file} type="file" hidden accept=".json,.syx" onChange={e=>e.target.files?.[0]&&void importFile(e.target.files[0])}/></div><p>A row is 32 slices with one algorithm. A column is one target through all 32 algorithms. Banks contain 32 DX7 patches; the table is a patch map, not a hardware wavetable playback mode.</p></div></section>
 </section><footer>DEXFRAGGLER <span>Anchor a path. Solve the table. Keep the discoveries.</span></footer></main>
}
