import { env } from 'cloudflare:workers';
import { database } from '@/db/storage';
import { SHAPES, MODEL, initialState, validatePatch, evaluate, clone } from '@/public/core.mjs';
import seeds from '@/public/legacy-seeds.json';
export const dynamic='force-dynamic';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
async function authorized(req:Request){const secret=(env as unknown as {DEXFRAGGLER_RUNNER_SECRET?:string}).DEXFRAGGLER_RUNNER_SECRET;const token=req.headers.get('x-dexfraggler-worker');if(secret&&token&&token.length===secret.length){const enc=new TextEncoder();const [a,b]=await Promise.all([crypto.subtle.digest('SHA-256',enc.encode(secret)),crypto.subtle.digest('SHA-256',enc.encode(token))]);if(new Uint8Array(a).every((v,i)=>v===new Uint8Array(b)[i]))return true}return !!req.headers.get('oai-authenticated-user-id')}
async function initialize(){const db=database();const r=await db.prepare('SELECT shape FROM runs').all();const have=new Set(r.results.map(x=>x.shape));for(const shape of SHAPES)if(!have.has(shape)){const state=initialState(shape,seeds);await db.prepare('INSERT OR IGNORE INTO runs(shape,state,updated_at) VALUES(?,?,?)').bind(shape,JSON.stringify(state),Date.now()).run()}}
function decode(row:Record<string,unknown>){return {...row,state:JSON.parse(String(row.state)),reference:row.reference?JSON.parse(String(row.reference)):null}}
export async function GET(req:Request){try{if(!await authorized(req))return json({error:'Sign in to load your experiments.'},401);await initialize();const db=database();const [runs,workers]=await Promise.all([db.prepare('SELECT * FROM runs ORDER BY shape').all(),db.prepare('SELECT * FROM workers ORDER BY last_seen DESC LIMIT 4').all()]);return json({runs:runs.results.map(decode),workers:workers.results,model:MODEL})}catch(e){console.error('Load experiments',e);return json({error:'Experiment storage is unavailable. Your saved work has not been replaced.'},503)}}
export async function POST(req:Request){try{if(!await authorized(req))return json({error:'Sign in to change experiments.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Origin is not allowed.'},403);const body=await req.text();if(body.length>450000)return json({error:'Import must be under 450 KB.'},413);const b=JSON.parse(body);const db=database();await initialize();if(b.action==='heartbeat'){if(typeof b.worker!=='string'||b.worker.length>100)return json({error:'Invalid worker.'},400);await db.prepare('INSERT INTO workers(id,last_seen,engine) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen=excluded.last_seen,engine=excluded.engine').bind(b.worker,Date.now(),String(b.engine||'PM model').slice(0,120)).run();return json({ok:true})}
 if(b.action==='claim'){if(typeof b.worker!=='string'||b.worker.length>100)return json({error:'Invalid worker.'},400);const now=Date.now();const row=await db.prepare('SELECT * FROM runs WHERE running=1 AND lease_until<? ORDER BY updated_at LIMIT 1').bind(now).first();if(!row)return json({run:null});const result=await db.prepare('UPDATE runs SET lease_owner=?,lease_until=? WHERE shape=? AND revision=? AND lease_until<? AND running=1').bind(b.worker,now+60000,row.shape,row.revision,now).run();return json({run:result.meta.changes?decode({...row,lease_owner:b.worker,lease_until:now+60000}):null})}
 if(!SHAPES.includes(b.shape))return json({error:'Select saw, square or triangle.'},400);const row=await db.prepare('SELECT * FROM runs WHERE shape=?').bind(b.shape).first();if(!row)return json({error:'Experiment not found.'},404);
 if(b.action==='running'){if(typeof b.running!=='boolean')return json({error:'Running must be true or false.'},400);await db.prepare('UPDATE runs SET running=?,revision=revision+1,lease_until=0,lease_owner=NULL WHERE shape=?').bind(b.running?1:0,b.shape).run();return json({ok:true})}
 if(b.action==='checkpoint'){if(row.lease_owner!==b.worker||row.revision!==b.revision||Number(row.lease_until)<Date.now()||row.running!==1)return json({error:'The experiment changed. Fetch its latest checkpoint.'},409);const state=b.state;if(!state||state.model!==MODEL||state.shape!==b.shape||!Number.isSafeInteger(state.evaluations)||state.evaluations<JSON.parse(String(row.state)).evaluations||state.evaluations>JSON.parse(String(row.state)).evaluations+100000||!Array.isArray(state.elites)||state.elites.length<1||state.elites.length>16||!Array.isArray(state.history)||state.history.length>120)return json({error:'Invalid checkpoint.'},400);for(const item of state.elites){validatePatch(item.patch);if(!Number.isFinite(item.loss)||item.loss<0||item.loss>5||!Number.isFinite(item.score)||item.score<0||item.score>1)return json({error:'Invalid score.'},400)}if(state.harmonics!==JSON.parse(String(row.state)).harmonics)return json({error:'Target bandwidth changed.'},409);const old=JSON.parse(String(row.state));if(state.elites[0].loss>old.elites[0].loss+1e-12)return json({error:'A checkpoint cannot discard a better solution.'},400);let reference=row.reference;if(b.reference){const r=b.reference;validatePatch(r.patch);if(r.engine!=='Dexed Mark I / native'||!Array.isArray(r.notes)||r.notes.length!==3||!r.notes.every((n:Record<string,unknown>)=>Number.isFinite(n.score)&&Number(n.score)>=0&&Number(n.score)<=1))return json({error:'Invalid reference measurement.'},400);if(!reference||r.loss<JSON.parse(String(reference)).loss)reference=JSON.stringify(r)}const result=await db.prepare('UPDATE runs SET state=?,reference=?,updated_at=?,revision=revision+1,lease_until=0,lease_owner=NULL WHERE shape=? AND revision=? AND lease_owner=? AND running=1').bind(JSON.stringify(state),reference,Date.now(),b.shape,b.revision,b.worker).run();return result.meta.changes?json({ok:true}):json({error:'Checkpoint superseded.'},409)}
 if(b.action==='import'||b.action==='configure'){const old=JSON.parse(String(row.state));let state=clone(old);if(b.action==='configure'){if(![16,32,64].includes(b.harmonics)||typeof b.allowDetune!=='boolean')return json({error:'Use 16, 32 or 64 harmonics.'},400);state=initialState(b.shape,old.elites.map((x:{patch:unknown})=>({target:b.shape,patch:x.patch,source:'Re-scored champion'})),b.harmonics);state.allowDetune=b.allowDetune}else{const input=b.patches;if(!Array.isArray(input)||input.length<1||input.length>64)return json({error:'Import 1–64 patches at a time.'},400);for(const raw of input){const p=validatePatch(raw.patch??raw);state.nativeSeeds=[p,...(state.nativeSeeds??[])].slice(0,64);const item=evaluate(p,b.shape,state.harmonics);state.elites.push({...item,source:'Imported / re-scored'});state.evaluations++}state.elites.sort((a:{loss:number},b:{loss:number})=>a.loss-b.loss);const seen=new Set();state.elites=state.elites.filter((x:{patch:unknown})=>{const key=JSON.stringify(x.patch);if(seen.has(key))return false;seen.add(key);return true}).slice(0,16)}const result=await db.prepare('UPDATE runs SET state=?,reference=?,revision=revision+1,lease_until=0,lease_owner=NULL,updated_at=? WHERE shape=? AND revision=?').bind(JSON.stringify(state),b.action==='configure'?null:row.reference,Date.now(),b.shape,row.revision).run();return result.meta.changes?json({ok:true}):json({error:'Experiment changed. Try the action again.'},409)}return json({error:'Unknown action.'},400)
 }catch(e){console.error('Experiment update',e);return json({error:e instanceof Error?e.message:'Unable to save this change.'},400)}}
