import {env} from 'cloudflare:workers';
import {database} from '@/db/storage';
import {MODEL,validatePatch,blank} from '@/public/core.mjs';
import {DEFAULT_CONFIG,validateConfig,columnTargets,targetKey,scheduleCell} from '@/public/targets.mjs';
export const dynamic='force-dynamic';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
async function auth(req:Request){const secret=(env as unknown as {DEXFRAGGLER_RUNNER_SECRET?:string}).DEXFRAGGLER_RUNNER_SECRET,token=req.headers.get('x-dexfraggler-worker');if(secret&&token&&secret.length===token.length){const enc=new TextEncoder(),[a,b]=await Promise.all([secret,token].map(s=>crypto.subtle.digest('SHA-256',enc.encode(s))));if(new Uint8Array(a).every((v,i)=>v===new Uint8Array(b)[i]))return true}return !!req.headers.get('oai-authenticated-user-id')}
async function board(){const db=database();await db.prepare('INSERT OR IGNORE INTO map_board(id,config) VALUES(1,?)').bind(JSON.stringify(DEFAULT_CONFIG)).run();return (await db.prepare('SELECT * FROM map_board WHERE id=1').first())!}
const parse=(x:unknown)=>x?JSON.parse(String(x)):null;
const decode=(c:Record<string,unknown>)=>({...c,algorithm:Math.floor(Number(c.id)/32)+1,slot:Number(c.id)%32,patch:parse(c.patch),state:parse(c.state),reference:parse(c.reference),seeds:parse(c.seeds),provenance:parse(c.provenance)});
function cellId(v:unknown){if(!Number.isInteger(v)||Number(v)<0||Number(v)>1023)throw Error('Choose an algorithm and slice from 1 to 32.');return Number(v)}
function rowPatch(raw:unknown,id:number){const p=validatePatch(raw);if(p.algorithm!==Math.floor(id/32)+1)throw Error('A patch must use the cell’s row algorithm.');return p}
async function summaries(){return (await database().prepare('SELECT id,target_key,visits,evaluations,model_score,native_score,native_loss,updated_at,revision,failed_until,last_error FROM map_cells').all()).results}
export async function GET(req:Request){try{if(!await auth(req))return json({error:'Sign in to load your table.'},401);const b=await board(),config=parse(b.config),keys=columnTargets(config).map(targetKey),url=new URL(req.url),db=database();if(url.searchParams.has('cell')){const id=cellId(Number(url.searchParams.get('cell'))),c=await db.prepare('SELECT * FROM map_cells WHERE id=?').bind(id).first();return json({cell:c?decode(c):null,config,revision:b.revision,target:columnTargets(config)[id%32]})}if(url.searchParams.has('export')){const cells=(await db.prepare("SELECT id,patch,target_key,model_score,native_score,native_loss,provenance,json_extract(reference,'$.patch') AS native_patch FROM map_cells ORDER BY id").all()).results.map(c=>({id:c.id,algorithm:Math.floor(Number(c.id)/32)+1,slot:Number(c.id)%32,patch:parse(c.patch),reference:c.native_patch?{patch:parse(c.native_patch),score:Number(c.native_score),loss:Number(c.native_loss)}:null,provenance:parse(c.provenance),modelScore:c.model_score===null?null:Number(c.model_score),current:c.target_key===keys[Number(c.id)%32]}));return json({format:'dexfraggler-table',version:2,config,model:MODEL,cells})}const [cells,workers]=await Promise.all([summaries(),db.prepare('SELECT * FROM workers ORDER BY last_seen DESC LIMIT 4').all()]);return json({config,revision:b.revision,generation:b.generation,running:!!b.running,activeId:Number(b.lease_until)>Date.now()?b.active_id:null,cells:cells.map(c=>({...c,current:c.target_key===keys[Number(c.id)%32],target_key:undefined})),workers:workers.results})}catch(e){return json({error:e instanceof Error?e.message:'Table unavailable.'},400)}}
export async function POST(req:Request){try{
 if(!await auth(req))return json({error:'Sign in to change your table.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Origin is not allowed.'},403);const text=await req.text();if(text.length>400000)return json({error:'Send a smaller batch (up to 64 cells).'},413);const x=JSON.parse(text),db=database(),b=await board(),config=parse(b.config);
 if(x.action==='heartbeat'){if(typeof x.worker!=='string'||x.worker.length>100)throw Error('Invalid worker.');await db.prepare('INSERT INTO workers(id,last_seen,engine) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen=excluded.last_seen,engine=excluded.engine').bind(x.worker,Date.now(),'Table scheduler · Dexed Mark I').run();return json({ok:true})}
 if(x.action==='running'){if(typeof x.running!=='boolean')throw Error('Running must be true or false.');await db.batch([db.prepare('UPDATE map_board SET running=?,revision=revision+1,lease_owner=NULL,lease_until=0,active_id=NULL WHERE id=1').bind(x.running?1:0),db.prepare('UPDATE runs SET running=0,revision=revision+1,lease_owner=NULL,lease_until=0')]);return json({ok:true})}
 if(x.action==='configure'){const next=validateConfig(x.config);columnTargets(next);if(x.revision!==b.revision)return json({error:'Table changed; reload before changing anchors.'},409);const r=await db.prepare('UPDATE map_board SET config=?,generation=generation+1,revision=revision+1,lease_owner=NULL,lease_until=0,active_id=NULL WHERE id=1 AND revision=?').bind(JSON.stringify(next),b.revision).run();return r.meta.changes?json({ok:true}):json({error:'Table changed; reload.'},409)}
 const targets=columnTargets(config),keys=targets.map(targetKey);
 if(x.action==='claim'){if(typeof x.worker!=='string'||x.worker.length>100)throw Error('Invalid worker.');if(!b.running||Number(b.lease_until)>Date.now())return json({job:null});const id=scheduleCell(await summaries(),config,keys),now=Date.now();if(id===null)return json({job:null});const r=await db.prepare('UPDATE map_board SET lease_owner=?,lease_until=?,active_id=? WHERE id=1 AND running=1 AND generation=? AND lease_until<?').bind(x.worker,now+60000,id,b.generation,now).run();if(!r.meta.changes)return json({job:null});const c=await db.prepare('SELECT * FROM map_cells WHERE id=?').bind(id).first();const neighbors=(await db.prepare('SELECT id,patch,reference FROM map_cells WHERE id>=? AND id<? AND id!=? ORDER BY ABS(id-?) LIMIT 6').bind(Math.floor(id/32)*32,Math.floor(id/32)*32+32,id,id).all()).results.map(n=>({id:n.id,patch:parse(n.reference)?.patch??parse(n.patch)}));return json({job:{id,algorithm:Math.floor(id/32)+1,slot:id%32,generation:b.generation,config,target:targets[id%32],targetKey:keys[id%32],cell:c?decode(c):null,neighbors}})}
 if(x.action==='checkpoint'){
  const id=cellId(x.id);if(!b.running||b.active_id!==id||b.lease_owner!==x.worker||b.generation!==x.generation||Number(b.lease_until)<Date.now())return json({error:'This search batch was superseded.'},409);
  const s=x.state,r=x.reference;if(!s||s.model!==MODEL||s.algorithm!==Math.floor(id/32)+1||targetKey(s.shape)!==keys[id%32]||s.harmonics!==config.harmonics||s.allowDetune!==config.allowDetune||!Number.isSafeInteger(s.evaluations)||s.evaluations<1||!Array.isArray(s.elites)||s.elites.length<1||s.elites.length>16||!Array.isArray(s.history)||s.history.length>120||!Array.isArray(s.nativeSeeds)||s.nativeSeeds.length>64)throw Error('Invalid cell checkpoint.');
  for(const e of s.elites){rowPatch(e.patch,id);if(!Number.isFinite(e.loss)||e.loss<0||e.loss>5||!Number.isFinite(e.score)||e.score<0||e.score>1)throw Error('Invalid candidate score.')}s.nativeSeeds.forEach((p:unknown)=>rowPatch(p,id));
  rowPatch(r?.patch,id);if(r.engine!=='Dexed Mark I / native'||!Number.isFinite(r.loss)||r.loss<0||r.loss>1||!Number.isFinite(r.score)||r.score<0||r.score>1||!Array.isArray(r.notes)||r.notes.length!==3||!r.notes.every((n:{note:number;score:number;error:number;wave:number[];target:number[]},i:number)=>n.note===[45,57,69][i]&&Number.isFinite(n.score)&&n.score>=0&&n.score<=1&&Number.isFinite(n.error)&&n.error>=0&&n.error<=1&&Array.isArray(n.wave)&&Array.isArray(n.target)&&n.wave.length<=512&&n.target.length<=512&&[...n.wave,...n.target].every(Number.isFinite)))throw Error('Invalid native measurement.');
  const old=await db.prepare('SELECT * FROM map_cells WHERE id=?').bind(id).first();const current=old?.target_key===keys[id%32];if(current&&(s.evaluations<Number(old?.evaluations)||s.evaluations>Number(old?.evaluations)+100000||s.elites[0].loss>parse(old?.state).elites[0].loss+1e-12||r.loss>Number(old?.native_loss)+1e-12))throw Error('A checkpoint cannot discard a better solution.');
  const results=await db.batch([db.prepare('INSERT INTO map_cells(id,patch,state,reference,target_key,visits,evaluations,model_score,native_score,native_loss,updated_at,revision) SELECT ?,?,?,?,?,?,?,?,?,?,?,1 WHERE EXISTS(SELECT 1 FROM map_board WHERE id=1 AND lease_owner=? AND generation=? AND running=1 AND active_id=?) ON CONFLICT(id) DO UPDATE SET patch=excluded.patch,state=excluded.state,reference=excluded.reference,target_key=excluded.target_key,visits=excluded.visits,evaluations=excluded.evaluations,model_score=excluded.model_score,native_score=excluded.native_score,native_loss=excluded.native_loss,updated_at=excluded.updated_at,revision=map_cells.revision+1,seeds=\'[]\',failed_until=0,last_error=NULL').bind(id,JSON.stringify(s.elites[0].patch),JSON.stringify(s),JSON.stringify(r),keys[id%32],current?Number(old?.visits)+1:1,s.evaluations,String(s.elites[0].score),String(r.score),String(r.loss),Date.now(),x.worker,x.generation,id),db.prepare('UPDATE map_board SET revision=revision+1,lease_owner=NULL,lease_until=0,active_id=NULL WHERE id=1 AND lease_owner=? AND generation=? AND running=1 AND active_id=?').bind(x.worker,x.generation,id)]);return results[0].meta.changes?json({ok:true}):json({error:'Checkpoint superseded.'},409)
 }
 if(x.action==='failed'){
  const id=cellId(x.id);if(b.lease_owner!==x.worker||b.active_id!==id||b.generation!==x.generation||!b.running)return json({error:'Batch superseded.'},409);const old=await db.prepare('SELECT patch FROM map_cells WHERE id=?').bind(id).first();const patch=blank();patch.algorithm=Math.floor(id/32)+1;await db.batch([db.prepare('INSERT INTO map_cells(id,patch,failed_until,last_error) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM map_board WHERE id=1 AND lease_owner=? AND generation=? AND running=1) ON CONFLICT(id) DO UPDATE SET failed_until=excluded.failed_until,last_error=excluded.last_error').bind(id,old?.patch??JSON.stringify(patch),Date.now()+300000,String(x.error||'Measurement failed.').slice(0,240),x.worker,x.generation),db.prepare('UPDATE map_board SET lease_owner=NULL,lease_until=0,active_id=NULL,revision=revision+1 WHERE id=1 AND lease_owner=?').bind(x.worker)]);return json({ok:true})
 }
 if(x.action==='import'){
  if(!Array.isArray(x.cells)||x.cells.length<1||x.cells.length>64)throw Error('Import 1–64 cells per batch.');const cells=x.cells.map((c:{id?:number;algorithm:number;slot:number;patch:unknown;provenance?:unknown})=>{if(c.id===undefined&&(!Number.isInteger(c.algorithm)||c.algorithm<1||c.algorithm>32||!Number.isInteger(c.slot)||c.slot<0||c.slot>31))throw Error('Invalid cell coordinates.');const id=cellId(c.id??(c.algorithm-1)*32+c.slot);const provenance=c.provenance??{source:'Imported'};if(JSON.stringify(provenance).length>4000)throw Error('Cell provenance must be under 4 KB.');return {id,patch:rowPatch(c.patch,id),provenance}});
  if(new Set(cells.map((c:{id:number})=>c.id)).size!==cells.length)throw Error('Each cell may appear once per import batch.');const statements=cells.map((c:{id:number;patch:unknown;provenance:unknown})=>db.prepare('INSERT INTO map_cells(id,patch,seeds,provenance) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET seeds=excluded.seeds,revision=map_cells.revision+1').bind(c.id,JSON.stringify(c.patch),JSON.stringify([c.patch]),JSON.stringify(c.provenance)));statements.push(db.prepare('UPDATE map_board SET revision=revision+1,lease_owner=NULL,lease_until=0,active_id=NULL WHERE id=1'));await db.batch(statements);return json({ok:true,count:cells.length})
 }
 return json({error:'Unknown table action.'},400)
 }catch(e){return json({error:e instanceof Error?e.message:'Unable to update table.'},400)}}
