import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {runBatch,clone,MODEL} from '../public/core.mjs';
import {Reference,nativeProposal} from './reference.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),configPath=process.argv[2]||root+'.runtime/runner-config.json';
const config=JSON.parse(await fs.readFile(configPath,'utf8'));
const id='Windows background runner';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let reference=new Reference();let stopping=false;process.on('SIGINT',()=>{stopping=true});process.on('SIGTERM',()=>{stopping=true});
const statePath=root+'.runtime/native-progress.json';let native={};try{native=JSON.parse(await fs.readFile(statePath,'utf8'))}catch{}
async function atomic(path,data){const temp=path+'.'+process.pid+'.tmp';await fs.writeFile(temp,JSON.stringify(data));for(let attempt=0;;attempt++){try{await fs.rename(temp,path);break}catch(e){if(attempt>=8||!['EPERM','EBUSY','EACCES'].includes(e.code))throw e;await sleep(30*(attempt+1))}}}
async function call(action){const r=await fetch(config.url+'/api/lab',{method:'POST',headers:{'Content-Type':'application/json','OAI-Sites-Authorization':'Bearer '+config.bypass,'x-dexfraggler-worker':config.secret},body:JSON.stringify(action),signal:AbortSignal.timeout(25000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw Error(`Site returned ${r.status} without JSON.`)}if(!r.ok)throw Error(`${r.status}: ${data.error||'Request failed.'}`);return data}
let failures=0;console.log(new Date().toISOString(),'Runner started; one compute lane.');
while(!stopping){try{await call({action:'heartbeat',worker:id,engine:'Dexed Mark I + mathematical fitting'});const claimOwner=id+' '+crypto.randomUUID();const {run}=await call({action:'claim',worker:claimOwner});if(!run){await sleep(5000);continue}const shape=run.shape;let resumed=run.state;try{const saved=JSON.parse(await fs.readFile(root+'.runtime/checkpoint-'+shape+'.json','utf8'));if(saved.baseRevision===run.revision&&saved.state.model===MODEL&&saved.state.harmonics===run.state.harmonics&&saved.state.evaluations>=run.state.evaluations)resumed=saved.state}catch{}const state=runBatch(resumed,900),h=state.harmonics;let record=native[shape];if(!record||record.harmonics!==h)record={harmonics:h,count:0,best:run.reference,checked:[]};if(run.reference&&(!record.best||run.reference.loss<record.best.loss))record.best=run.reference;let measuredSeeds=0;for(const p of [state.elites[0].patch,...(state.nativeSeeds??[])]){const key=JSON.stringify(p);if(record.checked.includes(key))continue;const measured=await reference.score(p,shape,h);if(!record.best||measured.loss<record.best.loss)record.best=measured;record.checked.push(key);record.checked=record.checked.slice(-128);if(++measuredSeeds>=3)break}const stopAt=Date.now()+1800;while(Date.now()<stopAt&&!stopping){const from=record.count%8===0?state.elites[Math.floor(record.count/8)%state.elites.length].patch:record.best.patch;const p=nativeProposal(from,record.count++,state.allowDetune);const trial=await reference.score(p,shape,h);if(trial.loss<record.best.loss)record.best=trial}native[shape]=record;await atomic(statePath,native);await atomic(root+'.runtime/checkpoint-'+shape+'.json',{format:'dexfraggler-experiment',version:1,shape,baseRevision:run.revision,state,reference:record.best});await call({action:'checkpoint',shape,worker:claimOwner,revision:run.revision,state,reference:record.best});console.log(new Date().toISOString(),shape,'candidates',state.evaluations,'native trials',record.count,'native worst',record.best.score.toFixed(6));failures=0;await sleep(2000)}catch(e){if(!reference.healthy){reference.close();reference=new Reference()}failures++;console.error(new Date().toISOString(),e.message);await sleep(Math.min(60000,5000*failures))}}
reference.close();console.log('Runner stopped; checkpoints retained.');
